In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('padel.csv')
df.replace(to_replace='#NAME?',value=np.nan,inplace=True)
df.replace(to_replace=r'^\s*$',value=np.nan,regex=True,inplace=True)
columns = df.columns
df = df.astype("float", errors = "ignore")
df = np.float32(df)
df[np.isnan(df)] = 0
df[np.isinf(df)] = 0
df=pd.DataFrame(df,columns=columns)
ncol = df.shape[1]-1
x = df.iloc[:,0:ncol]
y = df['active']
corr_matrix = x.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
x1 = x.drop(to_drop, axis=1)
x2 = x1.loc[:, (x1 != x1.iloc[0]).any()] 
x2 = x2.round(6)

In [2]:
x1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE1_D,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP
0,0.0,-0.5644,0.318547,47.543701,74.387413,22.0,0.0,5.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
1,0.0,0.3078,0.094741,52.823002,44.257858,6.0,0.0,3.0,1.0,0.0,...,0.051235,0.002697,-5.645543,1.356911e+02,7.141639,9.329724,35.580002,0.000000,14.690436,1.415
2,0.0,-1.0727,1.150685,93.090698,77.521790,12.0,0.0,5.0,4.0,0.0,...,0.514679,0.014297,-2.391165,3.713096e+02,10.314156,21.301331,98.660004,3.044522,0.000000,3.166
3,0.0,-1.4939,2.231737,24.015100,22.764757,5.0,0.0,6.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
4,0.0,-1.3468,1.813870,69.866600,69.042999,12.0,0.0,3.0,3.0,0.0,...,0.146592,0.004729,-5.952321,2.530366e+02,8.162471,17.153955,90.459999,2.397895,16.841803,5.567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,0.0,2.3283,5.420981,67.304199,40.111446,0.0,0.0,0.0,1.0,0.0,...,0.249107,0.016607,-2.084809,8.790775e+01,5.860517,6.714432,17.070000,0.000000,2.456459,4.356
2020,0.0,0.0777,0.006037,29.923599,46.257858,12.0,0.0,2.0,1.0,0.0,...,0.000000,0.000000,-71.116287,3.000092e+06,150004.609375,29.828306,23.549999,0.000000,9.296835,5.566
2021,0.0,-1.7093,2.921706,17.461399,24.118723,6.0,0.0,1.0,2.0,0.0,...,0.033641,0.003058,-3.731219,6.601173e+01,6.001067,4.608816,66.480003,0.000000,7.402304,0.074
2022,1.0,-0.9485,0.899652,75.366203,54.621376,0.0,0.0,0.0,2.0,0.0,...,0.028600,0.001430,-7.108672,1.702734e+02,8.513672,10.274811,37.299999,0.000000,4.764172,7.865
2023,0.0,-10.4814,109.859749,194.479797,127.427582,0.0,0.0,0.0,30.0,0.0,...,0.000000,0.000000,-221.218307,9.036049e+02,13.690983,44.922188,474.899994,0.000000,0.000000,-11.796

In [3]:
x1.to_csv('output_file.csv')

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_val_test,y_train,y_val_test = train_test_split(x2,y,test_size = 0.2,random_state = 4)
x_val, x_test, y_val, y_test = train_test_split(x_val_test,y_val_test,test_size = 0.5,random_state = 4)

In [5]:
train = pd.concat([x_train,y_train],axis=1)
train

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1410,0.0,3.0305,9.183930,72.632301,40.683067,0.0,0.0,0.0,2.0,3.0,...,0.015920,-2.101535,7.910022e+01,5.650015,6.119002,110.959999,0.000000,17.571701,4.167,0.0
256,0.0,-2.0643,4.261334,137.133408,129.054443,18.0,0.0,1.0,14.0,0.0,...,0.008916,-3.675263,1.813097e+03,29.243504,46.517311,221.289993,0.000000,0.000000,6.152,1.0
1433,0.0,0.0179,0.000320,79.853104,55.047791,0.0,0.0,0.0,2.0,0.0,...,0.002507,-6.182847,3.796344e+02,18.077829,12.472338,37.299999,2.397895,5.084656,4.498,0.0
836,0.0,0.3900,0.152100,31.576099,32.013721,6.0,0.0,2.0,4.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0
1519,0.0,-1.9507,3.805230,20.520500,19.363516,0.0,0.0,0.0,1.0,0.0,...,0.001636,-3.128850,2.815074e+01,4.021534,2.336301,20.230000,0.000000,2.490697,1.329,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,2.0,-0.9760,0.952576,33.667599,47.431103,12.0,0.0,0.0,8.0,0.0,...,0.000000,-87.314407,2.903757e+02,11.168296,14.745057,127.199997,0.000000,20.885477,4.734,0.0
709,0.0,-0.0768,0.005898,27.020000,47.215858,15.0,0.0,2.0,0.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
439,0.0,-0.8807,0.775632,5.864600,29.023136,13.0,0.0,1.0,1.0,0.0,...,0.001811,-5.144823,9.865002e+01,7.046430,6.428210,36.020000,0.000000,0.000000,0.000,1.0
174,0.0,2.4088,5.802317,161.783600,113.287613,0.0,0.0,0.0,12.0,0.0,...,0.000000,-179.943008,6.000388e+06,122456.906250,76.475937,128.410004,3.044522,0.000000,0.000,1.0
1146,0.0,-1.3541,1.833587,26.947901,32.065895,6.0,0.0,1.0,2.0,0.0,...,0.017770,-1.947674,1.292882e+02,9.234872,6.806862,52.320000,0.000000,8.028066,3.314,0.0

In [6]:
val = pd.concat([x_val,y_val],axis=1)
val

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1313,0.0,1.8507,3.425090,24.732901,13.887551,0.0,0.0,0.0,0.0,0.0,...,0.012162,-1.399999,12.375955,2.475191,1.257878,0.000000,0.000000,2.329115,1.713,0.0
963,0.0,3.9345,15.480290,95.704803,54.672203,0.0,0.0,0.0,1.0,0.0,...,0.012520,-2.805362,230.636902,10.982710,11.425774,17.070000,0.000000,2.405903,6.335,1.0
253,0.0,0.0100,0.000100,51.623901,55.703861,15.0,0.0,2.0,4.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,73.580002,2.397895,17.130220,2.963,1.0
1999,0.0,0.4317,0.186365,37.693001,24.592688,0.0,0.0,0.0,2.0,0.0,...,0.009050,-2.257026,33.808239,3.756471,3.168634,29.459999,0.000000,5.192114,1.071,0.0
1652,0.0,-0.4883,0.238437,20.504299,25.878723,6.0,0.0,1.0,2.0,0.0,...,0.012847,-2.243660,65.788483,5.482374,5.023734,52.320000,0.000000,7.889287,2.387,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
698,0.0,-0.9901,0.980298,35.611000,60.811825,16.0,0.0,1.0,1.0,0.0,...,0.004416,-5.627582,307.377960,11.822229,14.893003,20.309999,0.000000,0.000000,0.000,1.0
1932,0.0,0.0000,0.000000,0.000000,43.201515,20.0,0.0,0.0,0.0,0.0,...,0.001988,-6.449960,217.276489,10.863824,10.762341,0.000000,2.397895,0.000000,10.212,0.0
1973,0.0,0.7788,0.606529,41.568802,27.686274,0.0,0.0,0.0,2.0,0.0,...,0.000000,-34.657360,38.078407,3.807841,3.639647,40.459999,0.000000,4.686580,1.262,0.0
1807,1.0,0.8730,0.762129,102.640800,71.317719,0.0,0.0,0.0,3.0,0.0,...,0.007235,-4.409089,737.690735,27.321878,17.829517,57.529999,2.397895,7.308397,8.263,0.0
1338,0.0,-0.4204,0.176736,3.300000,17.193966,9.0,0.0,3.0,0.0,0.0,...,0.006053,-2.618977,48.314964,5.368329,3.489967,41.570000,2.397895,9.129371,1.957,0.0

In [28]:
test1 = pd.concat([x_test,y_test],axis=1)
test1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1207,0.0,-0.4487,0.201332,7.276800,18.456345,6.0,0.0,0.0,1.0,0.0,...,0.009695,-2.045387,52.854477,6.606809,3.174034,20.230000,0.000000,2.452455,2.409,0.0
1126,0.0,-0.4603,0.211876,2.564600,28.589930,12.0,0.0,0.0,1.0,0.0,...,0.003717,-3.938825,72.218536,5.555272,5.563606,20.230000,0.000000,2.547069,5.063,0.0
301,0.0,0.2718,0.073875,150.591995,98.367233,0.0,0.0,0.0,7.0,0.0,...,0.000974,-12.980343,1204.721558,30.118038,28.376015,94.449997,3.433987,0.000000,0.000,1.0
1266,0.0,3.2452,10.531323,42.030201,17.053585,0.0,0.0,0.0,0.0,0.0,...,0.000000,-21.210304,15.318544,2.553091,1.637438,0.000000,0.000000,9.301424,3.928,0.0
1800,0.0,-0.9440,0.891136,101.295303,62.623997,0.0,0.0,0.0,5.0,0.0,...,0.000968,-10.101781,325.169159,11.613185,16.196169,94.830002,2.397895,15.115392,1.138,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1330,0.0,0.0112,0.000125,11.988400,21.018345,6.0,0.0,0.0,2.0,0.0,...,0.005470,-2.905887,107.358070,10.735807,4.676170,26.299999,0.000000,5.179036,2.987,0.0
1366,0.0,1.2962,1.680134,17.525101,20.149172,6.0,0.0,0.0,1.0,0.0,...,0.004453,-3.111654,79.314499,7.931450,4.373421,17.070000,0.000000,7.472410,2.639,0.0
2016,0.0,0.6767,0.457923,11.700700,19.847551,6.0,0.0,1.0,0.0,0.0,...,0.009446,-2.218438,74.262833,8.251426,3.876850,23.790001,0.000000,2.451677,3.100,0.0
707,0.0,-1.6816,2.827779,13.200000,54.668690,24.0,0.0,8.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
138,0.0,-2.2485,5.055752,62.584400,59.539375,6.0,0.0,2.0,1.0,0.0,...,0.000350,-11.088125,262.379150,11.407789,12.810518,23.549999,0.000000,9.257409,5.270,1.0

In [8]:
col_name = train.columns.values.tolist()
col_name.pop()

'active'

In [9]:
from pycaret.classification import *
CM = setup(data = train, target = 'active', test_data = val, silent=True, numeric_features = col_name,
             session_id=0, fold_strategy = 'stratifiedkfold', fold = 5, fold_shuffle = True, normalize = True, normalize_method = 'minmax')

In [10]:
mlp = create_model('mlp')
tunedmlp = tune_model(mlp,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedmlp)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.772104,0.035339,0.090869,0.071731,0.00000,0.0,0.000000,0.000000,0.0,...,8.839968e-07,0.000004,0.016448,0.000000,0.000000,0.057366,0.271806,0.0,0.0,0.9676
1,0.00,0.909669,0.159719,0.351621,0.282388,0.00000,0.0,0.000000,0.034483,0.0,...,1.647406e-05,0.000016,0.149404,0.045887,0.000000,0.059257,0.570000,1.0,1.0,0.6786
2,0.00,0.650587,0.000001,0.189667,0.287716,0.46875,0.0,0.181818,0.137931,0.0,...,0.000000e+00,0.000000,0.000000,0.197796,0.477927,0.421916,0.352452,1.0,1.0,0.8454
3,0.00,0.678426,0.001923,0.138485,0.127024,0.00000,0.0,0.000000,0.068966,0.0,...,2.414874e-06,0.000006,0.041433,0.079194,0.000000,0.127881,0.230387,0.0,0.0,0.9672
4,0.00,0.617691,0.002460,0.075333,0.133666,0.18750,0.0,0.090909,0.068966,0.0,...,4.699178e-06,0.000008,0.065690,0.140645,0.000000,0.194312,0.315290,0.0,0.0,0.9836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.584564,0.010114,0.130835,0.314099,0.50000,0.0,0.090909,0.034483,0.0,...,2.195557e-05,0.000018,0.194741,0.054597,0.000000,0.000000,0.161290,1.0,1.0,0.7797
198,0.00,0.649927,0.000000,0.000000,0.223140,0.62500,0.0,0.000000,0.000000,0.0,...,1.551975e-05,0.000016,0.140728,0.000000,0.477927,0.000000,0.820129,0.0,0.0,0.9062
199,0.00,0.701341,0.006258,0.152724,0.143003,0.00000,0.0,0.000000,0.068966,0.0,...,2.719886e-06,0.000006,0.047592,0.108763,0.000000,0.115430,0.242710,0.0,0.0,0.9524
200,0.25,0.707560,0.007863,0.377104,0.368363,0.00000,0.0,0.000000,0.103448,0.0,...,5.269220e-05,0.000041,0.233139,0.154651,0.477927,0.180005,0.694387,0.0,0.0,0.7809
201,0.00,0.622174,0.001823,0.012124,0.088809,0.28125,0.0,0.272727,0.000000,0.0,...,3.451069e-06,0.000008,0.045635,0.111747,0.477927,0.224855,0.287548,0.0,0.0,0.8743

In [11]:
xgb = create_model('xgboost')
tunedxgb = tune_model(xgb,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedxgb)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.772104,0.035339,0.090869,0.071731,0.00000,0.0,0.000000,0.000000,0.0,...,8.839968e-07,0.000004,0.016448,0.000000,0.000000,0.057366,0.271806,0.0,0.0,0.9993
1,0.00,0.909669,0.159719,0.351621,0.282388,0.00000,0.0,0.000000,0.034483,0.0,...,1.647406e-05,0.000016,0.149404,0.045887,0.000000,0.059257,0.570000,1.0,1.0,0.9989
2,0.00,0.650587,0.000001,0.189667,0.287716,0.46875,0.0,0.181818,0.137931,0.0,...,0.000000e+00,0.000000,0.000000,0.197796,0.477927,0.421916,0.352452,1.0,1.0,0.9994
3,0.00,0.678426,0.001923,0.138485,0.127024,0.00000,0.0,0.000000,0.068966,0.0,...,2.414874e-06,0.000006,0.041433,0.079194,0.000000,0.127881,0.230387,0.0,0.0,0.9996
4,0.00,0.617691,0.002460,0.075333,0.133666,0.18750,0.0,0.090909,0.068966,0.0,...,4.699178e-06,0.000008,0.065690,0.140645,0.000000,0.194312,0.315290,0.0,0.0,0.9998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.584564,0.010114,0.130835,0.314099,0.50000,0.0,0.090909,0.034483,0.0,...,2.195557e-05,0.000018,0.194741,0.054597,0.000000,0.000000,0.161290,1.0,1.0,0.9995
198,0.00,0.649927,0.000000,0.000000,0.223140,0.62500,0.0,0.000000,0.000000,0.0,...,1.551975e-05,0.000016,0.140728,0.000000,0.477927,0.000000,0.820129,0.0,0.0,0.9755
199,0.00,0.701341,0.006258,0.152724,0.143003,0.00000,0.0,0.000000,0.068966,0.0,...,2.719886e-06,0.000006,0.047592,0.108763,0.000000,0.115430,0.242710,0.0,0.0,0.9994
200,0.25,0.707560,0.007863,0.377104,0.368363,0.00000,0.0,0.000000,0.103448,0.0,...,5.269220e-05,0.000041,0.233139,0.154651,0.477927,0.180005,0.694387,0.0,0.0,0.5073
201,0.00,0.622174,0.001823,0.012124,0.088809,0.28125,0.0,0.272727,0.000000,0.0,...,3.451069e-06,0.000008,0.045635,0.111747,0.477927,0.224855,0.287548,0.0,0.0,0.9703

In [12]:
rf = create_model('rf')
tunedrf = tune_model(rf, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedrf)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.772104,0.035339,0.090869,0.071731,0.00000,0.0,0.000000,0.000000,0.0,...,8.839968e-07,0.000004,0.016448,0.000000,0.000000,0.057366,0.271806,0.0,0.0,0.9980
1,0.00,0.909669,0.159719,0.351621,0.282388,0.00000,0.0,0.000000,0.034483,0.0,...,1.647406e-05,0.000016,0.149404,0.045887,0.000000,0.059257,0.570000,1.0,1.0,0.7984
2,0.00,0.650587,0.000001,0.189667,0.287716,0.46875,0.0,0.181818,0.137931,0.0,...,0.000000e+00,0.000000,0.000000,0.197796,0.477927,0.421916,0.352452,1.0,1.0,0.9087
3,0.00,0.678426,0.001923,0.138485,0.127024,0.00000,0.0,0.000000,0.068966,0.0,...,2.414874e-06,0.000006,0.041433,0.079194,0.000000,0.127881,0.230387,0.0,0.0,0.9871
4,0.00,0.617691,0.002460,0.075333,0.133666,0.18750,0.0,0.090909,0.068966,0.0,...,4.699178e-06,0.000008,0.065690,0.140645,0.000000,0.194312,0.315290,0.0,0.0,0.9880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.584564,0.010114,0.130835,0.314099,0.50000,0.0,0.090909,0.034483,0.0,...,2.195557e-05,0.000018,0.194741,0.054597,0.000000,0.000000,0.161290,1.0,1.0,0.8048
198,0.00,0.649927,0.000000,0.000000,0.223140,0.62500,0.0,0.000000,0.000000,0.0,...,1.551975e-05,0.000016,0.140728,0.000000,0.477927,0.000000,0.820129,0.0,0.0,0.8535
199,0.00,0.701341,0.006258,0.152724,0.143003,0.00000,0.0,0.000000,0.068966,0.0,...,2.719886e-06,0.000006,0.047592,0.108763,0.000000,0.115430,0.242710,0.0,0.0,0.9609
200,0.25,0.707560,0.007863,0.377104,0.368363,0.00000,0.0,0.000000,0.103448,0.0,...,5.269220e-05,0.000041,0.233139,0.154651,0.477927,0.180005,0.694387,0.0,0.0,0.7441
201,0.00,0.622174,0.001823,0.012124,0.088809,0.28125,0.0,0.272727,0.000000,0.0,...,3.451069e-06,0.000008,0.045635,0.111747,0.477927,0.224855,0.287548,0.0,0.0,0.9358

In [13]:
et = create_model('et')
tunedet = tune_model(et, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedet)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.772104,0.035339,0.090869,0.071731,0.00000,0.0,0.000000,0.000000,0.0,...,8.839968e-07,0.000004,0.016448,0.000000,0.000000,0.057366,0.271806,0.0,0.0,0.9958
1,0.00,0.909669,0.159719,0.351621,0.282388,0.00000,0.0,0.000000,0.034483,0.0,...,1.647406e-05,0.000016,0.149404,0.045887,0.000000,0.059257,0.570000,1.0,1.0,0.6774
2,0.00,0.650587,0.000001,0.189667,0.287716,0.46875,0.0,0.181818,0.137931,0.0,...,0.000000e+00,0.000000,0.000000,0.197796,0.477927,0.421916,0.352452,1.0,1.0,0.9023
3,0.00,0.678426,0.001923,0.138485,0.127024,0.00000,0.0,0.000000,0.068966,0.0,...,2.414874e-06,0.000006,0.041433,0.079194,0.000000,0.127881,0.230387,0.0,0.0,0.9769
4,0.00,0.617691,0.002460,0.075333,0.133666,0.18750,0.0,0.090909,0.068966,0.0,...,4.699178e-06,0.000008,0.065690,0.140645,0.000000,0.194312,0.315290,0.0,0.0,0.9905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.584564,0.010114,0.130835,0.314099,0.50000,0.0,0.090909,0.034483,0.0,...,2.195557e-05,0.000018,0.194741,0.054597,0.000000,0.000000,0.161290,1.0,1.0,0.7696
198,0.00,0.649927,0.000000,0.000000,0.223140,0.62500,0.0,0.000000,0.000000,0.0,...,1.551975e-05,0.000016,0.140728,0.000000,0.477927,0.000000,0.820129,0.0,0.0,0.8630
199,0.00,0.701341,0.006258,0.152724,0.143003,0.00000,0.0,0.000000,0.068966,0.0,...,2.719886e-06,0.000006,0.047592,0.108763,0.000000,0.115430,0.242710,0.0,0.0,0.9576
200,0.25,0.707560,0.007863,0.377104,0.368363,0.00000,0.0,0.000000,0.103448,0.0,...,5.269220e-05,0.000041,0.233139,0.154651,0.477927,0.180005,0.694387,0.0,0.0,0.6815
201,0.00,0.622174,0.001823,0.012124,0.088809,0.28125,0.0,0.272727,0.000000,0.0,...,3.451069e-06,0.000008,0.045635,0.111747,0.477927,0.224855,0.287548,0.0,0.0,0.9169

In [14]:
catboost = create_model('catboost')
tunedcat1 = tune_model(catboost, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedcat1)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.772104,0.035339,0.090869,0.071731,0.00000,0.0,0.000000,0.000000,0.0,...,8.839968e-07,0.000004,0.016448,0.000000,0.000000,0.057366,0.271806,0.0,0.0,0.9974
1,0.00,0.909669,0.159719,0.351621,0.282388,0.00000,0.0,0.000000,0.034483,0.0,...,1.647406e-05,0.000016,0.149404,0.045887,0.000000,0.059257,0.570000,1.0,1.0,0.9565
2,0.00,0.650587,0.000001,0.189667,0.287716,0.46875,0.0,0.181818,0.137931,0.0,...,0.000000e+00,0.000000,0.000000,0.197796,0.477927,0.421916,0.352452,1.0,1.0,0.9678
3,0.00,0.678426,0.001923,0.138485,0.127024,0.00000,0.0,0.000000,0.068966,0.0,...,2.414874e-06,0.000006,0.041433,0.079194,0.000000,0.127881,0.230387,0.0,0.0,0.9996
4,0.00,0.617691,0.002460,0.075333,0.133666,0.18750,0.0,0.090909,0.068966,0.0,...,4.699178e-06,0.000008,0.065690,0.140645,0.000000,0.194312,0.315290,0.0,0.0,0.9990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.584564,0.010114,0.130835,0.314099,0.50000,0.0,0.090909,0.034483,0.0,...,2.195557e-05,0.000018,0.194741,0.054597,0.000000,0.000000,0.161290,1.0,1.0,0.6704
198,0.00,0.649927,0.000000,0.000000,0.223140,0.62500,0.0,0.000000,0.000000,0.0,...,1.551975e-05,0.000016,0.140728,0.000000,0.477927,0.000000,0.820129,0.0,0.0,0.9776
199,0.00,0.701341,0.006258,0.152724,0.143003,0.00000,0.0,0.000000,0.068966,0.0,...,2.719886e-06,0.000006,0.047592,0.108763,0.000000,0.115430,0.242710,0.0,0.0,0.9994
200,0.25,0.707560,0.007863,0.377104,0.368363,0.00000,0.0,0.000000,0.103448,0.0,...,5.269220e-05,0.000041,0.233139,0.154651,0.477927,0.180005,0.694387,0.0,0.0,0.9215
201,0.00,0.622174,0.001823,0.012124,0.088809,0.28125,0.0,0.272727,0.000000,0.0,...,3.451069e-06,0.000008,0.045635,0.111747,0.477927,0.224855,0.287548,0.0,0.0,0.9901

In [15]:
lightgbm = create_model('lightgbm')
tunedlightgbm = tune_model(lightgbm,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedlightgbm)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.772104,0.035339,0.090869,0.071731,0.00000,0.0,0.000000,0.000000,0.0,...,8.839968e-07,0.000004,0.016448,0.000000,0.000000,0.057366,0.271806,0.0,0.0,1.0000
1,0.00,0.909669,0.159719,0.351621,0.282388,0.00000,0.0,0.000000,0.034483,0.0,...,1.647406e-05,0.000016,0.149404,0.045887,0.000000,0.059257,0.570000,1.0,1.0,1.0000
2,0.00,0.650587,0.000001,0.189667,0.287716,0.46875,0.0,0.181818,0.137931,0.0,...,0.000000e+00,0.000000,0.000000,0.197796,0.477927,0.421916,0.352452,1.0,1.0,1.0000
3,0.00,0.678426,0.001923,0.138485,0.127024,0.00000,0.0,0.000000,0.068966,0.0,...,2.414874e-06,0.000006,0.041433,0.079194,0.000000,0.127881,0.230387,0.0,0.0,1.0000
4,0.00,0.617691,0.002460,0.075333,0.133666,0.18750,0.0,0.090909,0.068966,0.0,...,4.699178e-06,0.000008,0.065690,0.140645,0.000000,0.194312,0.315290,0.0,0.0,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.584564,0.010114,0.130835,0.314099,0.50000,0.0,0.090909,0.034483,0.0,...,2.195557e-05,0.000018,0.194741,0.054597,0.000000,0.000000,0.161290,1.0,1.0,0.9993
198,0.00,0.649927,0.000000,0.000000,0.223140,0.62500,0.0,0.000000,0.000000,0.0,...,1.551975e-05,0.000016,0.140728,0.000000,0.477927,0.000000,0.820129,0.0,0.0,0.9999
199,0.00,0.701341,0.006258,0.152724,0.143003,0.00000,0.0,0.000000,0.068966,0.0,...,2.719886e-06,0.000006,0.047592,0.108763,0.000000,0.115430,0.242710,0.0,0.0,1.0000
200,0.25,0.707560,0.007863,0.377104,0.368363,0.00000,0.0,0.000000,0.103448,0.0,...,5.269220e-05,0.000041,0.233139,0.154651,0.477927,0.180005,0.694387,0.0,0.0,1.0000
201,0.00,0.622174,0.001823,0.012124,0.088809,0.28125,0.0,0.272727,0.000000,0.0,...,3.451069e-06,0.000008,0.045635,0.111747,0.477927,0.224855,0.287548,0.0,0.0,1.0000

In [26]:
from itertools import combinations
ml = [tunedrf, tunedet, tunedlightgbm, tunedcat1, tunedxgb,tunedmlp]
a2 =  list(combinations(ml, 2))
a3 =  list(combinations(ml, 3))
a4 =  list(combinations(ml, 4))
a5 =  list(combinations(ml, 5))
a6 =  list(combinations(ml, 6))

all = a2 + a3 + a4 + a5 + a6 
print(len(all))
print(len(a2),len(a3),len(a4),len(a5),len(a6))

57
15 20 15 6 1

In [17]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['Accuracy']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=0, verbose=0,
                     warm_start=False), LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=0, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)) 0.9356

In [27]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['AUC']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(LGBMClassifier(bagging_fraction=1.0, bagging_freq=0, boosting_type='gbdt',
               class_weight=None, colsample_bytree=1.0,
               feature_fraction=0.5356066564543145, importance_type='split',
               learning_rate=0.49999999999999994, max_depth=-1,
               min_child_samples=31, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=300, n_jobs=-1, num_leaves=123, objective=None,
               random_state=0, reg_alpha=3.919960677534761e-07,
               reg_lambda=1.8318144166206812e-08, silent='warn', subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0), XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.5,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.24369069487018535, max_bin=256,
              max_cat_to_onehot=4, max_delta_step=0, max_depth=9, max_leaves=0,
              min_child_weight=4, missing=nan, monotone_constraints='()',
              n_estimators=300, n_jobs=-1, num_parallel_tree=1,
              objective='binary:logistic', predictor='auto', random_state=0,
              reg_alpha=1.0506792519008158e-10, ...)) 0.9698
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Warning] feature_fraction is set=0.5356066564543145, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5356066564543145
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Warning] feature_fraction is set=0.5356066564543145, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5356066564543145
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0

In [29]:
blend = blend_models([tunedxgb, tunedlightgbm])
md = predict_model(blend,data = test1)
md
y_pred = md['Label']
y_true = md['active']
t = y_pred.astype(float)
t
from sklearn.metrics import balanced_accuracy_score
accuracy = balanced_accuracy_score(y_true, t)
accuracy

0.8911064425770308