In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('padel.csv')
df.replace(to_replace='#NAME?',value=np.nan,inplace=True)
df.replace(to_replace=r'^\s*$',value=np.nan,regex=True,inplace=True)
columns = df.columns
df = df.astype("float", errors = "ignore")
df = np.float32(df)
df[np.isnan(df)] = 0
df[np.isinf(df)] = 0
df=pd.DataFrame(df,columns=columns)
ncol = df.shape[1]-1
x = df.iloc[:,0:ncol]
y = df['active']
corr_matrix = x.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
x1 = x.drop(to_drop, axis=1)
x2 = x1.loc[:, (x1 != x1.iloc[0]).any()] 
x2 = x2.round(6)

In [2]:
x1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE1_D,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP
0,0.0,-0.5644,0.318547,47.543701,74.387413,22.0,0.0,5.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
1,0.0,0.3078,0.094741,52.823002,44.257858,6.0,0.0,3.0,1.0,0.0,...,0.051235,0.002697,-5.645543,1.356911e+02,7.141639,9.329724,35.580002,0.000000,14.690436,1.415
2,0.0,-1.0727,1.150685,93.090698,77.521790,12.0,0.0,5.0,4.0,0.0,...,0.514679,0.014297,-2.391165,3.713096e+02,10.314156,21.301331,98.660004,3.044522,0.000000,3.166
3,0.0,-1.4939,2.231737,24.015100,22.764757,5.0,0.0,6.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
4,0.0,-1.3468,1.813870,69.866600,69.042999,12.0,0.0,3.0,3.0,0.0,...,0.146592,0.004729,-5.952321,2.530366e+02,8.162471,17.153955,90.459999,2.397895,16.841803,5.567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,0.0,2.3283,5.420981,67.304199,40.111446,0.0,0.0,0.0,1.0,0.0,...,0.249107,0.016607,-2.084809,8.790775e+01,5.860517,6.714432,17.070000,0.000000,2.456459,4.356
2020,0.0,0.0777,0.006037,29.923599,46.257858,12.0,0.0,2.0,1.0,0.0,...,0.000000,0.000000,-71.116287,3.000092e+06,150004.609375,29.828306,23.549999,0.000000,9.296835,5.566
2021,0.0,-1.7093,2.921706,17.461399,24.118723,6.0,0.0,1.0,2.0,0.0,...,0.033641,0.003058,-3.731219,6.601173e+01,6.001067,4.608816,66.480003,0.000000,7.402304,0.074
2022,1.0,-0.9485,0.899652,75.366203,54.621376,0.0,0.0,0.0,2.0,0.0,...,0.028600,0.001430,-7.108672,1.702734e+02,8.513672,10.274811,37.299999,0.000000,4.764172,7.865
2023,0.0,-10.4814,109.859749,194.479797,127.427582,0.0,0.0,0.0,30.0,0.0,...,0.000000,0.000000,-221.218307,9.036049e+02,13.690983,44.922188,474.899994,0.000000,0.000000,-11.796

In [3]:
x1.to_csv('output_file.csv')

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_val_test,y_train,y_val_test = train_test_split(x2,y,test_size = 0.2,random_state = 1)
x_val, x_test, y_val, y_test = train_test_split(x_val_test,y_val_test,test_size = 0.5,random_state = 1)

In [5]:
train = pd.concat([x_train,y_train],axis=1)
train

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
49,0.0,2.0296,4.119276,51.648800,70.129478,23.0,0.0,3.0,2.0,1.0,...,0.004414,-6.448294,325.794098,9.582180,19.673304,79.980003,3.044522,23.470591,7.440,1.0
1709,0.0,0.5906,0.348808,7.793500,12.607172,5.0,0.0,0.0,0.0,1.0,...,0.000000,0.000000,13.967595,2.793519,1.318370,28.240000,2.397895,2.875000,2.119,0.0
2009,0.0,-1.7849,3.185868,34.599602,41.153069,6.0,0.0,1.0,2.0,1.0,...,0.001564,-6.166875,207.588898,12.211112,9.070451,54.549999,0.000000,11.473117,3.632,0.0
1700,0.0,-0.7886,0.621890,32.787102,33.145103,6.0,0.0,2.0,5.0,0.0,...,0.008163,-3.357437,743.293945,43.723175,11.238856,104.860001,0.000000,18.789061,0.181,0.0
1873,0.0,0.3069,0.094188,10.350500,20.747931,6.0,0.0,0.0,0.0,0.0,...,0.009695,-2.045387,52.854477,6.606809,3.174034,0.000000,0.000000,0.000000,4.954,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1791,0.0,-0.5513,0.303932,15.831700,23.316723,6.0,0.0,1.0,1.0,0.0,...,0.011351,-2.175876,64.222458,6.422246,4.162353,35.250000,0.000000,5.423216,1.745,0.0
1096,0.0,0.5906,0.348808,7.793500,19.653963,9.0,0.0,1.0,0.0,1.0,...,0.006053,-2.618977,48.314964,5.368329,3.489967,41.130001,2.397895,6.100841,2.140,0.0
1932,0.0,0.0000,0.000000,0.000000,43.201515,20.0,0.0,0.0,0.0,0.0,...,0.001988,-6.449960,217.276489,10.863824,10.762341,0.000000,2.397895,0.000000,10.212,0.0
235,0.0,0.2724,0.074202,44.724300,56.668652,17.0,0.0,3.0,3.0,0.0,...,0.006810,-4.572636,270.211426,10.007830,15.117853,58.400002,2.397895,0.000000,0.000,1.0
1061,0.0,0.0191,0.000365,9.032500,13.240758,5.0,0.0,2.0,0.0,0.0,...,0.008855,-1.761029,43.830784,7.305130,2.268202,28.680000,2.397895,5.790741,0.388,0.0

In [6]:
val = pd.concat([x_val,y_val],axis=1)
val

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
979,0.0,0.3447,0.118818,49.790298,40.737514,6.0,0.0,3.0,3.0,2.0,...,0.006313,-4.029309,1.465934e+02,7.715445,9.476560,127.449997,0.000000,0.000000,0.000,1.0
321,0.0,-0.1277,0.016307,169.867706,114.955956,0.0,0.0,1.0,4.0,0.0,...,0.001664,-11.501834,6.780684e+02,15.410645,28.684692,66.839996,0.000000,0.000000,0.000,1.0
1370,0.0,-0.0625,0.003906,39.261101,22.791929,0.0,0.0,2.0,2.0,0.0,...,0.000000,-41.172943,2.000028e+06,181820.703125,15.959539,58.200001,0.000000,10.714988,-0.069,0.0
1960,0.0,0.5519,0.304594,11.909500,18.635965,6.0,0.0,0.0,1.0,0.0,...,0.009446,-2.218438,7.426283e+01,8.251426,3.876850,17.070000,0.000000,4.965266,2.754,0.0
700,0.0,0.4328,0.187316,135.567398,99.389648,6.0,0.0,2.0,5.0,0.0,...,0.006254,-5.579879,4.788421e+02,11.679075,25.302620,0.000000,0.000000,0.000000,0.000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,0.0,0.7559,0.571385,10.327800,19.167553,6.0,0.0,0.0,0.0,0.0,...,0.009695,-2.045387,5.285448e+01,6.606809,3.174034,0.000000,0.000000,2.452455,3.883,0.0
1653,0.0,2.4692,6.096949,49.753601,30.404274,0.0,0.0,0.0,1.0,0.0,...,0.009956,-2.432877,4.888856e+01,4.444414,4.278498,20.230000,0.000000,2.400011,2.468,0.0
259,1.0,-0.4267,0.182073,68.240402,67.398239,12.0,0.0,5.0,4.0,0.0,...,0.009241,-3.950710,4.473803e+02,12.782294,21.361931,102.309998,0.000000,31.537077,4.307,1.0
1086,0.0,2.4893,6.196614,50.239300,29.070688,0.0,0.0,0.0,1.0,0.0,...,0.001455,-4.548638,5.509841e+01,5.008946,4.410033,17.070000,0.000000,2.404409,2.701,0.0
1081,0.0,0.3552,0.126167,34.549099,40.754311,11.0,0.0,1.0,3.0,0.0,...,0.001556,-6.939582,1.637874e+02,8.189372,10.197139,62.130001,2.397895,13.166405,2.405,0.0

In [26]:
test1 = pd.concat([x_test,y_test],axis=1)
test1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
655,0.0,-3.0380,9.229444,105.338203,68.764961,0.0,0.0,0.0,7.0,0.0,...,0.006583,-4.866344,476.004669,15.866823,18.496283,132.130005,2.397895,17.801794,-0.414,1.0
957,0.0,0.3238,0.104846,22.565599,10.573586,0.0,0.0,2.0,0.0,0.0,...,0.000000,-21.626192,18.981178,3.163530,1.766069,47.580002,0.000000,4.776650,-0.200,1.0
1976,0.0,1.9622,3.850229,13.282100,21.728758,6.0,0.0,2.0,4.0,0.0,...,0.001602,-5.032973,132.231812,10.171678,6.349924,86.279999,0.000000,15.730958,2.893,0.0
292,0.0,0.9347,0.873664,72.464104,69.343445,17.0,0.0,5.0,2.0,2.0,...,0.003043,-7.453734,432.303680,13.509490,19.421211,131.970001,0.000000,0.000000,0.000,1.0
1183,0.0,-1.3541,1.833587,26.947901,32.065895,6.0,0.0,1.0,2.0,0.0,...,0.012694,-2.418617,159.211487,11.372249,7.098327,52.320000,0.000000,8.014176,2.674,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
653,0.0,-0.4396,0.193248,43.991001,66.633446,22.0,0.0,7.0,2.0,0.0,...,0.000988,-11.295606,425.929199,12.906945,19.979101,105.349998,3.044522,29.770279,3.486,1.0
177,0.0,-1.2604,1.588608,89.533699,59.213791,0.0,0.0,0.0,5.0,0.0,...,0.004300,-5.575617,229.005600,9.160224,13.584366,97.989998,2.397895,0.000000,0.000,1.0
1775,0.0,-0.1567,0.024555,20.184999,26.403517,6.0,0.0,0.0,1.0,0.0,...,0.009676,-2.464264,56.188538,5.108049,4.431584,17.070000,0.000000,2.388462,3.914,0.0
1426,0.0,0.4062,0.164998,14.660400,22.253551,6.0,0.0,1.0,3.0,0.0,...,0.000000,-41.588833,61.669003,5.139083,4.946138,60.209999,0.000000,10.281086,2.396,0.0
108,0.0,-1.5384,2.366675,18.658001,43.570309,19.0,0.0,7.0,1.0,0.0,...,0.007933,-3.912860,224.050781,9.741339,12.447307,117.239998,2.397895,0.000000,0.000,1.0

In [8]:
col_name = train.columns.values.tolist()
col_name.pop()

'active'

In [9]:
from pycaret.classification import *
CM = setup(data = train, target = 'active', test_data = val, silent=True, numeric_features = col_name,
             session_id=0, fold_strategy = 'stratifiedkfold', fold = 5, fold_shuffle = True, normalize = True, normalize_method = 'minmax')

In [10]:
mlp = create_model('mlp')
tunedmlp = tune_model(mlp,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedmlp)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.596696,0.001082,0.182930,0.210414,0.18750,0.0,0.272727,0.100000,0.5,...,0.000010,0.000008,0.110281,0.268372,0.000000,0.000000,0.384523,1.0,1.0,0.7923
1,0.00,0.570659,0.000148,0.624096,0.593760,0.00000,0.0,0.090909,0.133333,0.0,...,0.000048,0.000015,0.333810,0.140745,0.000000,0.000000,0.384523,1.0,1.0,0.9639
2,0.00,0.574253,0.000036,0.144246,0.117723,0.00000,0.0,0.181818,0.066667,0.0,...,0.142859,0.181821,0.185725,0.122552,0.000000,0.276763,0.382273,0.0,0.0,0.9135
3,0.00,0.608116,0.002773,0.043756,0.096257,0.18750,0.0,0.000000,0.033333,0.0,...,0.000005,0.000008,0.045116,0.035944,0.000000,0.128250,0.474297,0.0,0.0,0.9275
4,0.00,0.601552,0.001705,0.498076,0.513358,0.18750,0.0,0.181818,0.166667,0.0,...,0.000034,0.000012,0.294452,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.619360,0.005201,0.037944,0.099002,0.18750,0.0,0.000000,0.000000,0.0,...,0.000004,0.000007,0.036937,0.000000,0.000000,0.063346,0.511100,0.0,0.0,0.9448
198,0.00,0.713791,0.055498,0.182795,0.157041,0.00000,0.0,0.000000,0.033333,0.0,...,0.000003,0.000004,0.049790,0.042598,0.000000,0.061991,0.464974,0.0,0.0,0.7092
199,0.25,0.554179,0.001657,0.250716,0.348119,0.37500,0.0,0.454545,0.133333,0.0,...,0.000032,0.000013,0.248593,0.215435,0.000000,0.814587,0.524921,1.0,1.0,0.9244
200,0.00,0.714899,0.056405,0.184580,0.150153,0.00000,0.0,0.000000,0.033333,0.0,...,0.000004,0.000005,0.051320,0.035944,0.000000,0.062105,0.472569,0.0,0.0,0.7623
201,0.00,0.597275,0.001148,0.126934,0.210500,0.34375,0.0,0.090909,0.100000,0.0,...,0.000012,0.000008,0.118666,0.130828,0.477927,0.340082,0.462920,0.0,1.0,0.6978

In [11]:
xgb = create_model('xgboost')
tunedxgb = tune_model(xgb,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedxgb)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.596696,0.001082,0.182930,0.210414,0.18750,0.0,0.272727,0.100000,0.5,...,0.000010,0.000008,0.110281,0.268372,0.000000,0.000000,0.384523,1.0,1.0,0.8722
1,0.00,0.570659,0.000148,0.624096,0.593760,0.00000,0.0,0.090909,0.133333,0.0,...,0.000048,0.000015,0.333810,0.140745,0.000000,0.000000,0.384523,1.0,1.0,0.9976
2,0.00,0.574253,0.000036,0.144246,0.117723,0.00000,0.0,0.181818,0.066667,0.0,...,0.142859,0.181821,0.185725,0.122552,0.000000,0.276763,0.382273,0.0,0.0,0.9208
3,0.00,0.608116,0.002773,0.043756,0.096257,0.18750,0.0,0.000000,0.033333,0.0,...,0.000005,0.000008,0.045116,0.035944,0.000000,0.128250,0.474297,0.0,0.0,0.9944
4,0.00,0.601552,0.001705,0.498076,0.513358,0.18750,0.0,0.181818,0.166667,0.0,...,0.000034,0.000012,0.294452,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.619360,0.005201,0.037944,0.099002,0.18750,0.0,0.000000,0.000000,0.0,...,0.000004,0.000007,0.036937,0.000000,0.000000,0.063346,0.511100,0.0,0.0,0.9924
198,0.00,0.713791,0.055498,0.182795,0.157041,0.00000,0.0,0.000000,0.033333,0.0,...,0.000003,0.000004,0.049790,0.042598,0.000000,0.061991,0.464974,0.0,0.0,0.9828
199,0.25,0.554179,0.001657,0.250716,0.348119,0.37500,0.0,0.454545,0.133333,0.0,...,0.000032,0.000013,0.248593,0.215435,0.000000,0.814587,0.524921,1.0,1.0,0.9930
200,0.00,0.714899,0.056405,0.184580,0.150153,0.00000,0.0,0.000000,0.033333,0.0,...,0.000004,0.000005,0.051320,0.035944,0.000000,0.062105,0.472569,0.0,0.0,0.7744
201,0.00,0.597275,0.001148,0.126934,0.210500,0.34375,0.0,0.090909,0.100000,0.0,...,0.000012,0.000008,0.118666,0.130828,0.477927,0.340082,0.462920,0.0,0.0,0.5244

In [12]:
rf = create_model('rf')
tunedrf = tune_model(rf, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedrf)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.596696,0.001082,0.182930,0.210414,0.18750,0.0,0.272727,0.100000,0.5,...,0.000010,0.000008,0.110281,0.268372,0.000000,0.000000,0.384523,1.0,1.0,0.7382
1,0.00,0.570659,0.000148,0.624096,0.593760,0.00000,0.0,0.090909,0.133333,0.0,...,0.000048,0.000015,0.333810,0.140745,0.000000,0.000000,0.384523,1.0,1.0,0.9348
2,0.00,0.574253,0.000036,0.144246,0.117723,0.00000,0.0,0.181818,0.066667,0.0,...,0.142859,0.181821,0.185725,0.122552,0.000000,0.276763,0.382273,0.0,0.0,0.8525
3,0.00,0.608116,0.002773,0.043756,0.096257,0.18750,0.0,0.000000,0.033333,0.0,...,0.000005,0.000008,0.045116,0.035944,0.000000,0.128250,0.474297,0.0,0.0,0.9991
4,0.00,0.601552,0.001705,0.498076,0.513358,0.18750,0.0,0.181818,0.166667,0.0,...,0.000034,0.000012,0.294452,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.619360,0.005201,0.037944,0.099002,0.18750,0.0,0.000000,0.000000,0.0,...,0.000004,0.000007,0.036937,0.000000,0.000000,0.063346,0.511100,0.0,0.0,0.9787
198,0.00,0.713791,0.055498,0.182795,0.157041,0.00000,0.0,0.000000,0.033333,0.0,...,0.000003,0.000004,0.049790,0.042598,0.000000,0.061991,0.464974,0.0,0.0,0.9851
199,0.25,0.554179,0.001657,0.250716,0.348119,0.37500,0.0,0.454545,0.133333,0.0,...,0.000032,0.000013,0.248593,0.215435,0.000000,0.814587,0.524921,1.0,1.0,0.9406
200,0.00,0.714899,0.056405,0.184580,0.150153,0.00000,0.0,0.000000,0.033333,0.0,...,0.000004,0.000005,0.051320,0.035944,0.000000,0.062105,0.472569,0.0,0.0,0.9504
201,0.00,0.597275,0.001148,0.126934,0.210500,0.34375,0.0,0.090909,0.100000,0.0,...,0.000012,0.000008,0.118666,0.130828,0.477927,0.340082,0.462920,0.0,0.0,0.6999

In [13]:
et = create_model('et')
tunedet = tune_model(et, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedet)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.596696,0.001082,0.182930,0.210414,0.18750,0.0,0.272727,0.100000,0.5,...,0.000010,0.000008,0.110281,0.268372,0.000000,0.000000,0.384523,1.0,1.0,0.7182
1,0.00,0.570659,0.000148,0.624096,0.593760,0.00000,0.0,0.090909,0.133333,0.0,...,0.000048,0.000015,0.333810,0.140745,0.000000,0.000000,0.384523,1.0,1.0,0.9396
2,0.00,0.574253,0.000036,0.144246,0.117723,0.00000,0.0,0.181818,0.066667,0.0,...,0.142859,0.181821,0.185725,0.122552,0.000000,0.276763,0.382273,0.0,0.0,0.8114
3,0.00,0.608116,0.002773,0.043756,0.096257,0.18750,0.0,0.000000,0.033333,0.0,...,0.000005,0.000008,0.045116,0.035944,0.000000,0.128250,0.474297,0.0,0.0,0.9924
4,0.00,0.601552,0.001705,0.498076,0.513358,0.18750,0.0,0.181818,0.166667,0.0,...,0.000034,0.000012,0.294452,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.619360,0.005201,0.037944,0.099002,0.18750,0.0,0.000000,0.000000,0.0,...,0.000004,0.000007,0.036937,0.000000,0.000000,0.063346,0.511100,0.0,0.0,0.9648
198,0.00,0.713791,0.055498,0.182795,0.157041,0.00000,0.0,0.000000,0.033333,0.0,...,0.000003,0.000004,0.049790,0.042598,0.000000,0.061991,0.464974,0.0,0.0,0.9551
199,0.25,0.554179,0.001657,0.250716,0.348119,0.37500,0.0,0.454545,0.133333,0.0,...,0.000032,0.000013,0.248593,0.215435,0.000000,0.814587,0.524921,1.0,1.0,0.9020
200,0.00,0.714899,0.056405,0.184580,0.150153,0.00000,0.0,0.000000,0.033333,0.0,...,0.000004,0.000005,0.051320,0.035944,0.000000,0.062105,0.472569,0.0,0.0,0.9209
201,0.00,0.597275,0.001148,0.126934,0.210500,0.34375,0.0,0.090909,0.100000,0.0,...,0.000012,0.000008,0.118666,0.130828,0.477927,0.340082,0.462920,0.0,0.0,0.7039

In [14]:
catboost = create_model('catboost')
tunedcat1 = tune_model(catboost, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedcat1)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.596696,0.001082,0.182930,0.210414,0.18750,0.0,0.272727,0.100000,0.5,...,0.000010,0.000008,0.110281,0.268372,0.000000,0.000000,0.384523,1.0,1.0,0.8054
1,0.00,0.570659,0.000148,0.624096,0.593760,0.00000,0.0,0.090909,0.133333,0.0,...,0.000048,0.000015,0.333810,0.140745,0.000000,0.000000,0.384523,1.0,1.0,0.9497
2,0.00,0.574253,0.000036,0.144246,0.117723,0.00000,0.0,0.181818,0.066667,0.0,...,0.142859,0.181821,0.185725,0.122552,0.000000,0.276763,0.382273,0.0,0.0,0.9510
3,0.00,0.608116,0.002773,0.043756,0.096257,0.18750,0.0,0.000000,0.033333,0.0,...,0.000005,0.000008,0.045116,0.035944,0.000000,0.128250,0.474297,0.0,0.0,0.9830
4,0.00,0.601552,0.001705,0.498076,0.513358,0.18750,0.0,0.181818,0.166667,0.0,...,0.000034,0.000012,0.294452,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.619360,0.005201,0.037944,0.099002,0.18750,0.0,0.000000,0.000000,0.0,...,0.000004,0.000007,0.036937,0.000000,0.000000,0.063346,0.511100,0.0,0.0,0.9859
198,0.00,0.713791,0.055498,0.182795,0.157041,0.00000,0.0,0.000000,0.033333,0.0,...,0.000003,0.000004,0.049790,0.042598,0.000000,0.061991,0.464974,0.0,0.0,0.9803
199,0.25,0.554179,0.001657,0.250716,0.348119,0.37500,0.0,0.454545,0.133333,0.0,...,0.000032,0.000013,0.248593,0.215435,0.000000,0.814587,0.524921,1.0,1.0,0.9518
200,0.00,0.714899,0.056405,0.184580,0.150153,0.00000,0.0,0.000000,0.033333,0.0,...,0.000004,0.000005,0.051320,0.035944,0.000000,0.062105,0.472569,0.0,0.0,0.9685
201,0.00,0.597275,0.001148,0.126934,0.210500,0.34375,0.0,0.090909,0.100000,0.0,...,0.000012,0.000008,0.118666,0.130828,0.477927,0.340082,0.462920,0.0,0.0,0.9112

In [15]:
lightgbm = create_model('lightgbm')
tunedlightgbm = tune_model(lightgbm,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedlightgbm)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.596696,0.001082,0.182930,0.210414,0.18750,0.0,0.272727,0.100000,0.5,...,0.000010,0.000008,0.110281,0.268372,0.000000,0.000000,0.384523,1.0,1.0,0.8714
1,0.00,0.570659,0.000148,0.624096,0.593760,0.00000,0.0,0.090909,0.133333,0.0,...,0.000048,0.000015,0.333810,0.140745,0.000000,0.000000,0.384523,1.0,1.0,0.9754
2,0.00,0.574253,0.000036,0.144246,0.117723,0.00000,0.0,0.181818,0.066667,0.0,...,0.142859,0.181821,0.185725,0.122552,0.000000,0.276763,0.382273,0.0,0.0,0.9673
3,0.00,0.608116,0.002773,0.043756,0.096257,0.18750,0.0,0.000000,0.033333,0.0,...,0.000005,0.000008,0.045116,0.035944,0.000000,0.128250,0.474297,0.0,0.0,0.9918
4,0.00,0.601552,0.001705,0.498076,0.513358,0.18750,0.0,0.181818,0.166667,0.0,...,0.000034,0.000012,0.294452,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.619360,0.005201,0.037944,0.099002,0.18750,0.0,0.000000,0.000000,0.0,...,0.000004,0.000007,0.036937,0.000000,0.000000,0.063346,0.511100,0.0,0.0,0.9922
198,0.00,0.713791,0.055498,0.182795,0.157041,0.00000,0.0,0.000000,0.033333,0.0,...,0.000003,0.000004,0.049790,0.042598,0.000000,0.061991,0.464974,0.0,0.0,0.9815
199,0.25,0.554179,0.001657,0.250716,0.348119,0.37500,0.0,0.454545,0.133333,0.0,...,0.000032,0.000013,0.248593,0.215435,0.000000,0.814587,0.524921,1.0,1.0,0.9586
200,0.00,0.714899,0.056405,0.184580,0.150153,0.00000,0.0,0.000000,0.033333,0.0,...,0.000004,0.000005,0.051320,0.035944,0.000000,0.062105,0.472569,0.0,0.0,0.8977
201,0.00,0.597275,0.001148,0.126934,0.210500,0.34375,0.0,0.090909,0.100000,0.0,...,0.000012,0.000008,0.118666,0.130828,0.477927,0.340082,0.462920,0.0,0.0,0.7683

In [23]:
from itertools import combinations
ml = [tunedrf, tunedet, tunedlightgbm, tunedcat1, tunedxgb,tunedmlp]
a2 =  list(combinations(ml, 2))
a3 =  list(combinations(ml, 3))
a4 =  list(combinations(ml, 4))
a5 =  list(combinations(ml, 5))
a6 =  list(combinations(ml, 6))

all = a2 + a3 + a4 + a5 + a6 
print(len(all))
print(len(a2),len(a3),len(a4),len(a5),len(a6))

57
15 20 15 6 1

In [17]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['Accuracy']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False), LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=0, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)) 0.8663

In [24]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['AUC']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=9, max_features=0.4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=1.3943180825636023e-05,
                       min_impurity_split=None, min_samples_leaf=3,
                       min_samples_split=10, min_weight_fraction_leaf=0.0,
                       n_estimators=135, n_jobs=-1, oob_score=False,
                       random_state=0, verbose=0, warm_start=False), LGBMClassifier(bagging_fraction=0.9715326767384609, bagging_freq=7,
               boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               feature_fraction=0.4, importance_type='split',
               learning_rate=0.05050070346562757, max_depth=-1,
               min_child_samples=37, min_child_weight=0.001,
               min_split_gain=0.9929833014053396, n_estimators=169, n_jobs=-1,
               num_leaves=206, objective=None, random_state=0,
               reg_alpha=1.81665057811389e-10, reg_lambda=0.0009319569989752274,
               silent='warn', subsample=1.0, subsample_for_bin=200000,
               subsample_freq=0)) 0.942
[LightGBM] [Warning] bagging_fraction is set=0.9715326767384609, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9715326767384609
[LightGBM] [Warning] feature_fraction is set=0.4, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4
[LightGBM] [Warning] bagging_freq is set=7, subsample_freq=0 will be ignored. Current value: bagging_freq=7
[LightGBM] [Warning] bagging_fraction is set=0.9715326767384609, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9715326767384609
[LightGBM] [Warning] feature_fraction is set=0.4, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4
[LightGBM] [Warning] bagging_freq is set=7, subsample_freq=0 will be ignored. Current value: bagging_freq=7
[LightGBM] [Warning] bagging_fraction is set=0.9715326767384609, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9715326767384609
[LightGBM] [Warning] feature_fraction is set=0.4, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4
[LightGBM] [Warning] bagging_freq is set=7, subsample_freq=0 will be ignored. Current value: bagging_freq=7

In [28]:
blend = blend_models([tunedrf,tunedlightgbm])
md = predict_model(blend,data = test1)
md
y_pred = md['Label']
y_true = md['active']
t = y_pred.astype(float)
t
from sklearn.metrics import balanced_accuracy_score
accuracy = balanced_accuracy_score(y_true, t)
accuracy

0.9197023110066589