In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('padel.csv')
df.replace(to_replace='#NAME?',value=np.nan,inplace=True)
df.replace(to_replace=r'^\s*$',value=np.nan,regex=True,inplace=True)
columns = df.columns
df = df.astype("float", errors = "ignore")
df = np.float32(df)
df[np.isnan(df)] = 0
df[np.isinf(df)] = 0
df=pd.DataFrame(df,columns=columns)
ncol = df.shape[1]-1
x = df.iloc[:,0:ncol]
y = df['active']
corr_matrix = x.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
x1 = x.drop(to_drop, axis=1)
x2 = x1.loc[:, (x1 != x1.iloc[0]).any()] 
x2 = x2.round(6)

In [2]:
x1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE1_D,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP
0,0.0,-0.5644,0.318547,47.543701,74.387413,22.0,0.0,5.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
1,0.0,0.3078,0.094741,52.823002,44.257858,6.0,0.0,3.0,1.0,0.0,...,0.051235,0.002697,-5.645543,1.356911e+02,7.141639,9.329724,35.580002,0.000000,14.690436,1.415
2,0.0,-1.0727,1.150685,93.090698,77.521790,12.0,0.0,5.0,4.0,0.0,...,0.514679,0.014297,-2.391165,3.713096e+02,10.314156,21.301331,98.660004,3.044522,0.000000,3.166
3,0.0,-1.4939,2.231737,24.015100,22.764757,5.0,0.0,6.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
4,0.0,-1.3468,1.813870,69.866600,69.042999,12.0,0.0,3.0,3.0,0.0,...,0.146592,0.004729,-5.952321,2.530366e+02,8.162471,17.153955,90.459999,2.397895,16.841803,5.567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,0.0,2.3283,5.420981,67.304199,40.111446,0.0,0.0,0.0,1.0,0.0,...,0.249107,0.016607,-2.084809,8.790775e+01,5.860517,6.714432,17.070000,0.000000,2.456459,4.356
2020,0.0,0.0777,0.006037,29.923599,46.257858,12.0,0.0,2.0,1.0,0.0,...,0.000000,0.000000,-71.116287,3.000092e+06,150004.609375,29.828306,23.549999,0.000000,9.296835,5.566
2021,0.0,-1.7093,2.921706,17.461399,24.118723,6.0,0.0,1.0,2.0,0.0,...,0.033641,0.003058,-3.731219,6.601173e+01,6.001067,4.608816,66.480003,0.000000,7.402304,0.074
2022,1.0,-0.9485,0.899652,75.366203,54.621376,0.0,0.0,0.0,2.0,0.0,...,0.028600,0.001430,-7.108672,1.702734e+02,8.513672,10.274811,37.299999,0.000000,4.764172,7.865
2023,0.0,-10.4814,109.859749,194.479797,127.427582,0.0,0.0,0.0,30.0,0.0,...,0.000000,0.000000,-221.218307,9.036049e+02,13.690983,44.922188,474.899994,0.000000,0.000000,-11.796

In [3]:
x1.to_csv('output_file.csv')

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_val_test,y_train,y_val_test = train_test_split(x2,y,test_size = 0.2,random_state = 0)
x_val, x_test, y_val, y_test = train_test_split(x_val_test,y_val_test,test_size = 0.5,random_state = 0)

In [5]:
train = pd.concat([x_train,y_train],axis=1)
train

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1056,1.0,-0.3467,0.120201,37.365101,26.352688,0.0,0.0,0.0,2.0,0.0,...,0.000000,-35.638187,5.000010e+06,500001.031250,15.424951,37.299999,0.000000,0.000000,0.000,0.0
805,0.0,-3.6181,13.090648,161.935898,125.650749,6.0,0.0,4.0,8.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0
1390,1.0,0.4472,0.199988,20.380400,10.174379,0.0,0.0,0.0,2.0,0.0,...,0.012162,-1.399999,1.237595e+01,2.475191,1.257878,37.299999,0.000000,6.955220,0.495,0.0
298,0.0,-0.8559,0.732565,49.573799,54.951859,12.0,0.0,0.0,8.0,0.0,...,0.007263,-4.459650,3.161690e+02,11.291750,16.117575,83.449997,0.000000,22.402775,0.832,1.0
52,0.0,-3.2630,10.647169,67.698303,102.060097,24.0,0.0,3.0,4.0,0.0,...,0.004939,-6.767285,7.897208e+02,17.549351,30.022556,0.000000,0.000000,19.229673,0.000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,1.0,-5.4747,29.972340,98.325897,101.537651,12.0,0.0,0.0,9.0,1.0,...,0.009028,-4.068852,5.359283e+02,12.463449,27.021202,0.000000,0.000000,0.000000,0.000,0.0
1216,0.0,-0.3829,0.146612,154.222794,104.022820,0.0,0.0,0.0,8.0,0.0,...,0.004428,-7.131698,8.056038e+02,18.734972,28.773846,110.139999,5.017280,0.000000,6.725,0.0
1653,0.0,2.4692,6.096949,49.753601,30.404274,0.0,0.0,0.0,1.0,0.0,...,0.009956,-2.432877,4.888856e+01,4.444414,4.278498,20.230000,0.000000,2.400011,2.468,0.0
559,0.0,-1.4996,2.248800,48.890499,70.078995,21.0,0.0,7.0,1.0,0.0,...,0.008160,-4.296922,2.931386e+02,9.160582,18.178066,100.779999,2.397895,0.000000,0.000,1.0
684,0.0,0.3573,0.127663,63.072102,75.287415,21.0,0.0,6.0,2.0,1.0,...,0.003715,-7.139860,1.059686e+03,30.276731,24.380047,113.629997,0.000000,0.000000,0.000,1.0

In [27]:
train.to_csv('padel_train.csv')

In [6]:
val = pd.concat([x_val,y_val],axis=1)
val

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
77,0.0,-0.4928,0.242852,27.906099,46.585896,17.0,0.0,3.0,2.0,0.0,...,0.002073,-7.000055,3.165701e+02,13.763916,13.242353,71.169998,2.397895,14.638543,5.681,1.0
553,0.0,-1.4882,2.214739,45.297001,68.491821,0.0,0.0,6.0,1.0,0.0,...,0.003777,-6.761499,4.527409e+02,14.148152,19.569023,92.089996,2.397895,23.960917,3.677,1.0
986,0.0,-0.0313,0.000980,27.101101,30.468687,6.0,0.0,2.0,0.0,0.0,...,0.000892,-5.444286,7.468739e+01,6.223949,5.175973,29.260000,0.000000,5.773470,2.211,1.0
997,0.0,0.4356,0.189747,28.582800,30.468687,6.0,0.0,2.0,0.0,0.0,...,0.000000,-40.795155,7.121037e+01,5.934198,5.118766,6.480000,0.000000,6.051521,1.994,1.0
1588,0.0,0.0171,0.000292,18.368000,25.076723,6.0,0.0,1.0,1.0,0.0,...,0.011002,-2.323007,7.264650e+01,6.604227,4.714166,29.100000,0.000000,5.327209,2.365,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,0.0,0.2988,0.089281,34.772301,51.929482,17.0,0.0,3.0,7.0,0.0,...,0.001624,-8.654297,3.987207e+02,14.240026,16.767132,118.980003,2.397895,0.000000,0.000,1.0
302,0.0,-2.7466,7.543812,42.993198,63.147034,16.0,0.0,3.0,2.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,59.060001,0.000000,0.000000,3.266,1.0
1175,0.0,-0.5514,0.304042,8.856300,31.953930,12.0,0.0,0.0,3.0,0.0,...,0.005179,-3.985001,1.070350e+02,6.689684,7.477049,46.529999,0.000000,8.142660,5.128,0.0
289,0.0,1.4732,2.170318,141.146393,103.580444,0.0,0.0,0.0,12.0,0.0,...,0.000000,-154.180649,6.000326e+06,133340.593750,70.232964,128.410004,0.000000,0.000000,0.000,1.0
229,0.0,-0.9531,0.908400,30.470699,47.387894,17.0,0.0,3.0,3.0,0.0,...,0.001811,-7.525770,3.034626e+02,12.644277,13.716620,91.400002,2.397895,17.159143,3.663,1.0

In [28]:
val.to_csv('padel_valid.csv')

In [33]:
test1 = pd.concat([x_test,y_test],axis=1)
test1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1211,0.0,-1.7529,3.072658,28.703100,18.838722,0.0,0.0,1.0,2.0,0.0,...,0.009185,-2.088556,33.639793,4.204974,2.812568,38.660000,0.000000,7.919106,2.710,0.0
249,0.0,-0.3333,0.111089,23.437000,51.693893,21.0,0.0,4.0,1.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
1379,0.0,-1.6034,2.570892,23.075800,39.112686,12.0,0.0,2.0,2.0,0.0,...,0.000000,-62.756996,123.964539,6.886919,8.675992,70.500000,0.000000,10.645683,1.812,0.0
519,0.0,0.9705,0.941870,119.424698,106.659309,17.0,0.0,4.0,7.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
264,0.0,-0.5102,0.260304,11.412100,34.225136,15.0,0.0,5.0,2.0,0.0,...,0.003485,-5.157965,304.271423,16.014284,10.864048,110.730003,2.397895,0.000000,0.000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146,0.0,-1.3541,1.833587,26.947901,32.065895,6.0,0.0,1.0,2.0,0.0,...,0.017770,-1.947674,129.288208,9.234872,6.806862,52.320000,0.000000,8.028066,3.314,0.0
399,0.0,-0.6300,0.396900,45.738098,68.312202,21.0,0.0,6.0,1.0,0.0,...,0.008447,-4.153886,319.424408,10.304013,17.876213,87.889999,0.000000,0.000000,0.000,1.0
1320,0.0,0.0908,0.008245,20.050501,10.522758,0.0,0.0,2.0,1.0,0.0,...,0.012162,-1.399999,12.375955,2.475191,1.257878,32.669998,0.000000,7.767499,-0.275,0.0
1064,0.0,-1.0582,1.119787,23.179199,18.029930,0.0,0.0,0.0,1.0,0.0,...,0.001636,-3.128850,28.150736,4.021534,2.336301,17.070000,0.000000,2.490697,0.920,0.0
1436,1.0,-1.8303,3.349998,46.931499,42.852276,6.0,0.0,2.0,5.0,0.0,...,0.003307,-5.600797,166.450272,7.926203,10.740863,118.720001,0.000000,17.972639,1.743,0.0

In [29]:
test.to_csv('padel_test.csv')

In [8]:
col_name = train.columns.values.tolist()
col_name.pop()

'active'

In [9]:
from pycaret.classification import *
CM = setup(data = train, target = 'active', test_data = val, silent=True, numeric_features = col_name,
             session_id=0, fold_strategy = 'stratifiedkfold', fold = 5, fold_shuffle = True, normalize = True, normalize_method = 'minmax')

In [10]:
mlp = create_model('mlp')
tunedmlp = tune_model(mlp,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedmlp)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.632823,0.002211,0.102527,0.240621,0.566667,0.0,0.272727,0.066667,0.0,...,0.000023,0.000014,0.154104,0.149863,0.477927,0.360546,0.569710,1.0,1.0,0.9457
1,0.0,0.569760,0.020160,0.166422,0.353767,0.000000,0.0,0.545455,0.033333,0.0,...,0.000032,0.000014,0.227729,0.193915,0.477927,0.590155,0.504384,1.0,1.0,0.9240
2,0.0,0.662061,0.000009,0.099570,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.060234,0.061613,0.000000,0.142200,0.456596,1.0,0.0,0.6524
3,0.0,0.691641,0.001727,0.105014,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.059568,0.013645,0.000000,0.149048,0.449522,1.0,0.0,0.7464
4,0.0,0.665127,0.000003,0.067484,0.129524,0.200000,0.0,0.090909,0.033333,0.0,...,0.000005,0.000007,0.054860,0.061276,0.000000,0.131209,0.461616,0.0,0.0,0.9450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.682974,0.000813,0.127754,0.268221,0.566667,0.0,0.272727,0.233333,0.0,...,0.000028,0.000014,0.195123,0.250537,0.477927,0.000000,0.384523,1.0,1.0,0.8996
198,0.0,0.490034,0.068668,0.157958,0.326161,0.533333,0.0,0.272727,0.066667,0.0,...,0.000000,0.000000,0.000000,0.124363,0.000000,0.000000,0.490987,1.0,1.0,0.8877
199,0.0,0.629110,0.002768,0.032538,0.165045,0.400000,0.0,0.000000,0.100000,0.0,...,0.000008,0.000007,0.087012,0.097979,0.000000,0.200553,0.551684,0.0,0.0,0.8041
200,0.0,0.757378,0.019755,0.518574,0.535004,0.000000,0.0,0.000000,0.400000,0.0,...,0.428595,0.133341,0.817316,0.270394,0.000000,0.000000,0.384523,1.0,1.0,0.9134
201,0.0,0.603661,0.008269,0.111950,0.244763,0.566667,0.0,0.272727,0.100000,0.0,...,0.000022,0.000013,0.159623,0.192462,0.477927,0.422628,0.503928,1.0,1.0,0.9461

In [11]:
xgb = create_model('xgboost')
tunedxgb = tune_model(xgb,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedxgb)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.632823,0.002211,0.102527,0.240621,0.566667,0.0,0.272727,0.066667,0.0,...,0.000023,0.000014,0.154104,0.149863,0.477927,0.360546,0.569710,1.0,1.0,0.8653
1,0.0,0.569760,0.020160,0.166422,0.353767,0.000000,0.0,0.545455,0.033333,0.0,...,0.000032,0.000014,0.227729,0.193915,0.477927,0.590155,0.504384,1.0,1.0,0.9272
2,0.0,0.662061,0.000009,0.099570,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.060234,0.061613,0.000000,0.142200,0.456596,1.0,0.0,0.9799
3,0.0,0.691641,0.001727,0.105014,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.059568,0.013645,0.000000,0.149048,0.449522,1.0,0.0,0.9743
4,0.0,0.665127,0.000003,0.067484,0.129524,0.200000,0.0,0.090909,0.033333,0.0,...,0.000005,0.000007,0.054860,0.061276,0.000000,0.131209,0.461616,0.0,0.0,0.9849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.682974,0.000813,0.127754,0.268221,0.566667,0.0,0.272727,0.233333,0.0,...,0.000028,0.000014,0.195123,0.250537,0.477927,0.000000,0.384523,1.0,1.0,0.9663
198,0.0,0.490034,0.068668,0.157958,0.326161,0.533333,0.0,0.272727,0.066667,0.0,...,0.000000,0.000000,0.000000,0.124363,0.000000,0.000000,0.490987,1.0,1.0,0.8684
199,0.0,0.629110,0.002768,0.032538,0.165045,0.400000,0.0,0.000000,0.100000,0.0,...,0.000008,0.000007,0.087012,0.097979,0.000000,0.200553,0.551684,0.0,0.0,0.9902
200,0.0,0.757378,0.019755,0.518574,0.535004,0.000000,0.0,0.000000,0.400000,0.0,...,0.428595,0.133341,0.817316,0.270394,0.000000,0.000000,0.384523,1.0,1.0,0.9480
201,0.0,0.603661,0.008269,0.111950,0.244763,0.566667,0.0,0.272727,0.100000,0.0,...,0.000022,0.000013,0.159623,0.192462,0.477927,0.422628,0.503928,1.0,1.0,0.8093

In [12]:
rf = create_model('rf')
tunedrf = tune_model(rf, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedrf)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.632823,0.002211,0.102527,0.240621,0.566667,0.0,0.272727,0.066667,0.0,...,0.000023,0.000014,0.154104,0.149863,0.477927,0.360546,0.569710,1.0,1.0,0.7492
1,0.0,0.569760,0.020160,0.166422,0.353767,0.000000,0.0,0.545455,0.033333,0.0,...,0.000032,0.000014,0.227729,0.193915,0.477927,0.590155,0.504384,1.0,1.0,0.8545
2,0.0,0.662061,0.000009,0.099570,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.060234,0.061613,0.000000,0.142200,0.456596,1.0,0.0,0.9794
3,0.0,0.691641,0.001727,0.105014,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.059568,0.013645,0.000000,0.149048,0.449522,1.0,0.0,0.9506
4,0.0,0.665127,0.000003,0.067484,0.129524,0.200000,0.0,0.090909,0.033333,0.0,...,0.000005,0.000007,0.054860,0.061276,0.000000,0.131209,0.461616,0.0,0.0,0.9825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.682974,0.000813,0.127754,0.268221,0.566667,0.0,0.272727,0.233333,0.0,...,0.000028,0.000014,0.195123,0.250537,0.477927,0.000000,0.384523,1.0,1.0,0.8802
198,0.0,0.490034,0.068668,0.157958,0.326161,0.533333,0.0,0.272727,0.066667,0.0,...,0.000000,0.000000,0.000000,0.124363,0.000000,0.000000,0.490987,1.0,1.0,0.8166
199,0.0,0.629110,0.002768,0.032538,0.165045,0.400000,0.0,0.000000,0.100000,0.0,...,0.000008,0.000007,0.087012,0.097979,0.000000,0.200553,0.551684,0.0,0.0,0.9896
200,0.0,0.757378,0.019755,0.518574,0.535004,0.000000,0.0,0.000000,0.400000,0.0,...,0.428595,0.133341,0.817316,0.270394,0.000000,0.000000,0.384523,1.0,1.0,0.8361
201,0.0,0.603661,0.008269,0.111950,0.244763,0.566667,0.0,0.272727,0.100000,0.0,...,0.000022,0.000013,0.159623,0.192462,0.477927,0.422628,0.503928,1.0,1.0,0.6937

In [13]:
et = create_model('et')
tunedet = tune_model(et, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedet)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.632823,0.002211,0.102527,0.240621,0.566667,0.0,0.272727,0.066667,0.0,...,0.000023,0.000014,0.154104,0.149863,0.477927,0.360546,0.569710,1.0,1.0,0.8079
1,0.0,0.569760,0.020160,0.166422,0.353767,0.000000,0.0,0.545455,0.033333,0.0,...,0.000032,0.000014,0.227729,0.193915,0.477927,0.590155,0.504384,1.0,1.0,0.8652
2,0.0,0.662061,0.000009,0.099570,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.060234,0.061613,0.000000,0.142200,0.456596,1.0,0.0,0.9784
3,0.0,0.691641,0.001727,0.105014,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.059568,0.013645,0.000000,0.149048,0.449522,1.0,0.0,0.9563
4,0.0,0.665127,0.000003,0.067484,0.129524,0.200000,0.0,0.090909,0.033333,0.0,...,0.000005,0.000007,0.054860,0.061276,0.000000,0.131209,0.461616,0.0,0.0,0.9897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.682974,0.000813,0.127754,0.268221,0.566667,0.0,0.272727,0.233333,0.0,...,0.000028,0.000014,0.195123,0.250537,0.477927,0.000000,0.384523,1.0,1.0,0.8707
198,0.0,0.490034,0.068668,0.157958,0.326161,0.533333,0.0,0.272727,0.066667,0.0,...,0.000000,0.000000,0.000000,0.124363,0.000000,0.000000,0.490987,1.0,1.0,0.7820
199,0.0,0.629110,0.002768,0.032538,0.165045,0.400000,0.0,0.000000,0.100000,0.0,...,0.000008,0.000007,0.087012,0.097979,0.000000,0.200553,0.551684,0.0,0.0,0.9949
200,0.0,0.757378,0.019755,0.518574,0.535004,0.000000,0.0,0.000000,0.400000,0.0,...,0.428595,0.133341,0.817316,0.270394,0.000000,0.000000,0.384523,1.0,1.0,0.8787
201,0.0,0.603661,0.008269,0.111950,0.244763,0.566667,0.0,0.272727,0.100000,0.0,...,0.000022,0.000013,0.159623,0.192462,0.477927,0.422628,0.503928,1.0,1.0,0.8093

In [14]:
catboost = create_model('catboost')
tunedcat1 = tune_model(catboost, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedcat1)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.632823,0.002211,0.102527,0.240621,0.566667,0.0,0.272727,0.066667,0.0,...,0.000023,0.000014,0.154104,0.149863,0.477927,0.360546,0.569710,1.0,1.0,0.5535
1,0.0,0.569760,0.020160,0.166422,0.353767,0.000000,0.0,0.545455,0.033333,0.0,...,0.000032,0.000014,0.227729,0.193915,0.477927,0.590155,0.504384,1.0,1.0,0.9414
2,0.0,0.662061,0.000009,0.099570,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.060234,0.061613,0.000000,0.142200,0.456596,1.0,0.0,0.9829
3,0.0,0.691641,0.001727,0.105014,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.059568,0.013645,0.000000,0.149048,0.449522,1.0,0.0,0.9749
4,0.0,0.665127,0.000003,0.067484,0.129524,0.200000,0.0,0.090909,0.033333,0.0,...,0.000005,0.000007,0.054860,0.061276,0.000000,0.131209,0.461616,0.0,0.0,0.9807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.682974,0.000813,0.127754,0.268221,0.566667,0.0,0.272727,0.233333,0.0,...,0.000028,0.000014,0.195123,0.250537,0.477927,0.000000,0.384523,1.0,1.0,0.9693
198,0.0,0.490034,0.068668,0.157958,0.326161,0.533333,0.0,0.272727,0.066667,0.0,...,0.000000,0.000000,0.000000,0.124363,0.000000,0.000000,0.490987,1.0,1.0,0.8921
199,0.0,0.629110,0.002768,0.032538,0.165045,0.400000,0.0,0.000000,0.100000,0.0,...,0.000008,0.000007,0.087012,0.097979,0.000000,0.200553,0.551684,0.0,0.0,0.9842
200,0.0,0.757378,0.019755,0.518574,0.535004,0.000000,0.0,0.000000,0.400000,0.0,...,0.428595,0.133341,0.817316,0.270394,0.000000,0.000000,0.384523,1.0,1.0,0.9271
201,0.0,0.603661,0.008269,0.111950,0.244763,0.566667,0.0,0.272727,0.100000,0.0,...,0.000022,0.000013,0.159623,0.192462,0.477927,0.422628,0.503928,1.0,1.0,0.6744

In [15]:
lightgbm = create_model('lightgbm')
tunedlightgbm = tune_model(lightgbm,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedlightgbm)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.632823,0.002211,0.102527,0.240621,0.566667,0.0,0.272727,0.066667,0.0,...,0.000023,0.000014,0.154104,0.149863,0.477927,0.360546,0.569710,1.0,1.0,0.9526
1,0.0,0.569760,0.020160,0.166422,0.353767,0.000000,0.0,0.545455,0.033333,0.0,...,0.000032,0.000014,0.227729,0.193915,0.477927,0.590155,0.504384,1.0,1.0,0.9948
2,0.0,0.662061,0.000009,0.099570,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.060234,0.061613,0.000000,0.142200,0.456596,1.0,0.0,0.9996
3,0.0,0.691641,0.001727,0.105014,0.157374,0.200000,0.0,0.181818,0.000000,0.0,...,0.000005,0.000006,0.059568,0.013645,0.000000,0.149048,0.449522,1.0,0.0,0.9996
4,0.0,0.665127,0.000003,0.067484,0.129524,0.200000,0.0,0.090909,0.033333,0.0,...,0.000005,0.000007,0.054860,0.061276,0.000000,0.131209,0.461616,0.0,0.0,0.9996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.682974,0.000813,0.127754,0.268221,0.566667,0.0,0.272727,0.233333,0.0,...,0.000028,0.000014,0.195123,0.250537,0.477927,0.000000,0.384523,1.0,1.0,0.9998
198,0.0,0.490034,0.068668,0.157958,0.326161,0.533333,0.0,0.272727,0.066667,0.0,...,0.000000,0.000000,0.000000,0.124363,0.000000,0.000000,0.490987,1.0,1.0,0.9984
199,0.0,0.629110,0.002768,0.032538,0.165045,0.400000,0.0,0.000000,0.100000,0.0,...,0.000008,0.000007,0.087012,0.097979,0.000000,0.200553,0.551684,0.0,0.0,0.9999
200,0.0,0.757378,0.019755,0.518574,0.535004,0.000000,0.0,0.000000,0.400000,0.0,...,0.428595,0.133341,0.817316,0.270394,0.000000,0.000000,0.384523,1.0,1.0,0.9982
201,0.0,0.603661,0.008269,0.111950,0.244763,0.566667,0.0,0.272727,0.100000,0.0,...,0.000022,0.000013,0.159623,0.192462,0.477927,0.422628,0.503928,1.0,1.0,0.9691

In [30]:
from itertools import combinations
ml = [tunedrf, tunedet, tunedlightgbm, tunedcat1, tunedxgb,tunedmlp]
a2 =  list(combinations(ml, 2))
a3 =  list(combinations(ml, 3))
a4 =  list(combinations(ml, 4))
a5 =  list(combinations(ml, 5))
a6 =  list(combinations(ml, 6))

all = a2 + a3 + a4 + a5 + a6 
print(len(all))
print(len(a2),len(a3),len(a4),len(a5),len(a6))

57
15 20 15 6 1

In [17]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['Accuracy']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=0, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0), XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=0, reg_alpha=0, ...)) 0.8663

In [31]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['AUC']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='entropy', max_depth=11, max_features=1.0,
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=2.7865868826302696e-07,
                     min_impurity_split=None, min_samples_leaf=1,
                     min_samples_split=10, min_weight_fraction_leaf=0.0,
                     n_estimators=300, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.5,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.02746495068253659, max_bin=256,
              max_cat_to_onehot=4, max_delta_step=0, max_depth=4, max_leaves=0,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=300, n_jobs=-1, num_parallel_tree=1,
              objective='binary:logistic', predictor='auto', random_state=0,
              reg_alpha=1.3894297669820592e-07, ...), MLPClassifier(activation='relu', alpha=0.9999999998999984, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=[84, 49], learning_rate='invscaling',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=0, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)) 0.9264
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Warning] feature_fraction is set=0.6474679451752136, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6474679451752136
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Warning] feature_fraction is set=0.6474679451752136, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6474679451752136
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Warning] feature_fraction is set=0.6474679451752136, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6474679451752136
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Warning] feature_fraction is set=0.6474679451752136, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6474679451752136
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4

In [34]:
blend = blend_models([tunedxgb,tunedmlp,tunedet])
md = predict_model(blend,data = test1)
md
y_pred = md['Label']
y_true = md['active']
t = y_pred.astype(float)
t
from sklearn.metrics import balanced_accuracy_score
accuracy = balanced_accuracy_score(y_true, t)
accuracy

0.9261816767165921

In [32]:
test

               Model  Accuracy     AUC  Recall   Prec.      F1  Kappa     MCC
0  Voting Classifier    0.8515  0.9221   0.866  0.8317  0.8485  0.703  0.7035