In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('rdkit.csv')
df.replace(to_replace='#NAME?',value=np.nan,inplace=True)
df.replace(to_replace=r'^\s*$',value=np.nan,regex=True,inplace=True)
columns = df.columns
df = df.astype("float", errors = "ignore")
df = np.float32(df)
df[np.isnan(df)] = 0
df[np.isinf(df)] = 0
df=pd.DataFrame(df,columns=columns)
ncol = df.shape[1]-1
x = df.iloc[:,0:ncol]
y = df['active']
corr_matrix = x.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
x1 = x.drop(to_drop, axis=1)
x2 = x1.loc[:, (x1 != x1.iloc[0]).any()] 
x2 = x2.round(6)

In [2]:
df

,0,1,2,3,4,5,6,7,8,9,...,187,188,189,190,191,192,193,194,195,active
0,1.726,1139.849976,27.711000,22.427999,22.427999,19.063,13.684,13.684,9.651,9.651,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0
1,1.869,610.760010,17.653999,14.957000,14.957000,11.091,9.370,9.370,9.654,9.654,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.884,650.023987,17.653999,14.840000,14.840000,11.091,9.222,9.222,9.423,9.423,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.860,775.122009,21.679001,17.461000,17.461000,13.316,10.449,10.449,10.455,10.455,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.837,671.614014,19.938999,16.941999,16.941999,12.475,10.377,10.377,10.474,10.474,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,2.806,220.039001,8.268000,6.066000,6.066000,5.236,3.408,3.408,2.343,2.343,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020,3.137,52.568001,4.992000,3.540000,5.052000,2.770,1.653,2.566,0.945,1.850,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021,3.055,64.829002,6.406000,5.322000,6.139000,3.808,2.825,3.234,1.390,1.798,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022,3.174,266.592010,14.891000,13.150000,13.150000,9.770,8.288,8.288,5.374,5.374,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
2023,2.810,294.460999,11.475000,10.339000,10.339000,6.970,5.848,5.848,5.132,5.132,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_val_test,y_train,y_val_test = train_test_split(x2,y,test_size = 0.2,random_state = 0)
x_val, x_test, y_val, y_test = train_test_split(x_val_test,y_val_test,test_size = 0.5,random_state = 0)

In [4]:
train = pd.concat([x_train,y_train],axis=1)
train

,0,1,2,14,15,16,17,18,19,20,...,186,187,188,189,191,192,193,194,195,active
1056,2.913,287.147003,8.975000,5.969,9.589,0.0,0.000,11.127000,6.286000,7.110000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
805,1.979,1126.571045,23.250000,4.923,10.114,0.0,23.159,34.187000,0.000000,27.657000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1390,2.332,90.702003,5.820000,0.000,0.000,0.0,0.000,0.000000,18.552999,19.261999,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
298,1.526,618.046997,16.941000,6.104,10.213,0.0,11.791,0.000000,30.992001,18.405001,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
52,1.759,1145.555908,21.250000,0.000,5.107,0.0,5.880,23.594000,46.261002,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,1.550,1006.195007,17.510000,0.000,4.795,0.0,5.783,12.170000,52.977001,12.842000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1216,3.732,320.050995,19.622999,0.000,9.589,0.0,11.939,50.733002,25.683001,25.683001,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1653,3.282,200.899994,7.724000,0.000,0.000,0.0,0.000,0.000000,5.687000,16.690001,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
559,1.035,1256.444092,26.493000,0.000,9.589,0.0,36.055,29.231001,61.589001,10.255000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
684,0.939,1688.480957,29.931999,5.626,14.384,0.0,36.055,40.563000,62.316002,16.320999,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [28]:
train.to_csv('rdkit_train.csv')

In [5]:
val = pd.concat([x_val,y_val],axis=1)
val

,0,1,2,14,15,16,17,18,19,20,...,186,187,188,189,191,192,193,194,195,active
77,1.419,1306.822998,25.167000,0.000000,5.107000,0.0,6.607000,36.032001,36.101002,11.891,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
553,0.974,1548.804932,29.388000,11.690000,19.177999,0.0,35.993000,44.953999,51.367001,15.155,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
986,0.952,1589.399048,43.445999,105.331001,45.959000,0.0,11.519000,42.051998,36.637001,51.146,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
997,3.069,537.690002,14.577000,12.576000,9.589000,0.0,27.141001,11.994000,0.000000,12.133,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1588,3.152,294.144012,8.431000,0.000000,10.114000,0.0,10.611000,0.000000,11.127000,6.066,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,1.964,718.431030,20.408001,0.000000,0.000000,0.0,0.000000,0.000000,65.643997,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
302,1.922,670.997986,18.361000,34.874001,24.909000,0.0,35.926998,11.994000,19.261999,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1175,2.489,397.955994,14.958000,0.000000,4.795000,0.0,5.969000,18.087999,18.528999,12.842,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
289,1.733,1036.984985,19.250000,0.000000,0.000000,0.0,12.711000,23.792999,33.882999,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
229,1.880,937.668030,17.389000,0.000000,4.795000,0.0,5.907000,28.919001,26.974001,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [29]:
val.to_csv('rdkit_valid.csv')

In [33]:
test1 = pd.concat([x_test,y_test],axis=1)
test1

,0,1,2,14,15,16,17,18,19,20,...,186,187,188,189,191,192,193,194,195,active
1211,3.380,316.559998,9.301,4.923000,10.114000,0.0,20.754999,0.000000,0.000000,12.133000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,1.519,1298.932983,21.916,0.000000,9.589000,0.0,17.691000,4.905000,39.834000,4.900000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1379,2.510,516.247986,13.121,0.000000,0.000000,0.0,4.491000,10.045000,16.700001,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
519,1.701,1129.147949,20.924,0.000000,5.107000,0.0,18.274000,36.189999,5.386000,5.563000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
264,2.004,1206.235962,26.079,11.876000,9.589000,0.0,19.261999,28.757999,22.254000,27.544001,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146,2.424,375.628998,9.096,0.000000,0.000000,0.0,0.000000,0.000000,4.473000,11.127000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
399,1.906,641.997986,18.525,40.660999,25.221001,0.0,29.958000,24.836000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1320,2.826,34.629002,4.284,0.000000,4.907000,0.0,0.000000,0.000000,0.000000,5.009000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1064,2.854,243.348999,8.975,0.000000,5.107000,0.0,0.000000,5.750000,18.777000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1436,3.825,55.458000,7.328,7.262000,0.000000,0.0,25.392000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
test.to_csv('rdkit_test.csv')

In [7]:
col_name = train.columns.values.tolist()
col_name.pop()

'active'

In [8]:
from pycaret.classification import *
CM = setup(data = train, target = 'active', test_data = val, silent=True, numeric_features = col_name,
             session_id=0, fold_strategy = 'stratifiedkfold', fold = 5, fold_shuffle = True, normalize = True, normalize_method = 'minmax')

In [9]:
mlp = create_model('mlp')
tunedmlp = tune_model(mlp,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedmlp)

,0,1,2,14,15,16,17,18,19,20,...,188,189,191,192,193,194,195,active,Label,Score
0,0.253348,0.534948,0.396331,0.000000,0.058829,0.0,0.077542,0.367392,0.351406,0.123305,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.7730
1,0.173898,0.634004,0.462803,0.057147,0.220917,0.0,0.422428,0.458364,0.500005,0.157151,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8178
2,0.169970,0.650621,0.684189,0.514917,0.529414,0.0,0.135192,0.428774,0.356623,0.530362,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8367
3,0.547938,0.220104,0.229559,0.061479,0.110458,0.0,0.318538,0.122294,0.000000,0.125814,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,0.0,0.8455
4,0.562757,0.120408,0.132772,0.000000,0.116506,0.0,0.124535,0.000000,0.108310,0.062902,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.9547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.350652,0.294090,0.321386,0.000000,0.000000,0.0,0.000000,0.000000,0.638977,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.7064
198,0.343153,0.274673,0.289150,0.170484,0.286934,0.0,0.421654,0.122294,0.187496,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8410
199,0.444385,0.162903,0.235559,0.000000,0.055235,0.0,0.070055,0.184430,0.180361,0.133166,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.7303
200,0.309409,0.424490,0.303150,0.000000,0.000000,0.0,0.149181,0.242600,0.329816,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.7081
201,0.335654,0.383835,0.273843,0.000000,0.055235,0.0,0.069327,0.294866,0.262564,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.8467

In [10]:
xgb = create_model('xgboost')
tunedxgb = tune_model(xgb,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedxgb)

,0,1,2,14,15,16,17,18,19,20,...,188,189,191,192,193,194,195,active,Label,Score
0,0.253348,0.534948,0.396331,0.000000,0.058829,0.0,0.077542,0.367392,0.351406,0.123305,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.9321
1,0.173898,0.634004,0.462803,0.057147,0.220917,0.0,0.422428,0.458364,0.500005,0.157151,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8653
2,0.169970,0.650621,0.684189,0.514917,0.529414,0.0,0.135192,0.428774,0.356623,0.530362,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8098
3,0.547938,0.220104,0.229559,0.061479,0.110458,0.0,0.318538,0.122294,0.000000,0.125814,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,0.0,0.7692
4,0.562757,0.120408,0.132772,0.000000,0.116506,0.0,0.124535,0.000000,0.108310,0.062902,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.9932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.350652,0.294090,0.321386,0.000000,0.000000,0.0,0.000000,0.000000,0.638977,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8915
198,0.343153,0.274673,0.289150,0.170484,0.286934,0.0,0.421654,0.122294,0.187496,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.9911
199,0.444385,0.162903,0.235559,0.000000,0.055235,0.0,0.070055,0.184430,0.180361,0.133166,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.9108
200,0.309409,0.424490,0.303150,0.000000,0.000000,0.0,0.149181,0.242600,0.329816,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.5964
201,0.335654,0.383835,0.273843,0.000000,0.055235,0.0,0.069327,0.294866,0.262564,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.9904

In [11]:
rf = create_model('rf')
tunedrf = tune_model(rf, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedrf)

,0,1,2,14,15,16,17,18,19,20,...,188,189,191,192,193,194,195,active,Label,Score
0,0.253348,0.534948,0.396331,0.000000,0.058829,0.0,0.077542,0.367392,0.351406,0.123305,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.7766
1,0.173898,0.634004,0.462803,0.057147,0.220917,0.0,0.422428,0.458364,0.500005,0.157151,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8708
2,0.169970,0.650621,0.684189,0.514917,0.529414,0.0,0.135192,0.428774,0.356623,0.530362,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.7747
3,0.547938,0.220104,0.229559,0.061479,0.110458,0.0,0.318538,0.122294,0.000000,0.125814,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,0.0,0.8187
4,0.562757,0.120408,0.132772,0.000000,0.116506,0.0,0.124535,0.000000,0.108310,0.062902,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.9701
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.350652,0.294090,0.321386,0.000000,0.000000,0.0,0.000000,0.000000,0.638977,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8699
198,0.343153,0.274673,0.289150,0.170484,0.286934,0.0,0.421654,0.122294,0.187496,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.9797
199,0.444385,0.162903,0.235559,0.000000,0.055235,0.0,0.070055,0.184430,0.180361,0.133166,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.6544
200,0.309409,0.424490,0.303150,0.000000,0.000000,0.0,0.149181,0.242600,0.329816,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.7778
201,0.335654,0.383835,0.273843,0.000000,0.055235,0.0,0.069327,0.294866,0.262564,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.9275

In [12]:
et = create_model('et')
tunedet = tune_model(et, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedet)

,0,1,2,14,15,16,17,18,19,20,...,188,189,191,192,193,194,195,active,Label,Score
0,0.253348,0.534948,0.396331,0.000000,0.058829,0.0,0.077542,0.367392,0.351406,0.123305,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.8573
1,0.173898,0.634004,0.462803,0.057147,0.220917,0.0,0.422428,0.458364,0.500005,0.157151,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8894
2,0.169970,0.650621,0.684189,0.514917,0.529414,0.0,0.135192,0.428774,0.356623,0.530362,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.7911
3,0.547938,0.220104,0.229559,0.061479,0.110458,0.0,0.318538,0.122294,0.000000,0.125814,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,0.0,0.8681
4,0.562757,0.120408,0.132772,0.000000,0.116506,0.0,0.124535,0.000000,0.108310,0.062902,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.9599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.350652,0.294090,0.321386,0.000000,0.000000,0.0,0.000000,0.000000,0.638977,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8339
198,0.343153,0.274673,0.289150,0.170484,0.286934,0.0,0.421654,0.122294,0.187496,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.9433
199,0.444385,0.162903,0.235559,0.000000,0.055235,0.0,0.070055,0.184430,0.180361,0.133166,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.7683
200,0.309409,0.424490,0.303150,0.000000,0.000000,0.0,0.149181,0.242600,0.329816,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.7478
201,0.335654,0.383835,0.273843,0.000000,0.055235,0.0,0.069327,0.294866,0.262564,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.9494

In [13]:
catboost = create_model('catboost')
tunedcat1 = tune_model(catboost, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedcat1)

,0,1,2,14,15,16,17,18,19,20,...,188,189,191,192,193,194,195,active,Label,Score
0,0.253348,0.534948,0.396331,0.000000,0.058829,0.0,0.077542,0.367392,0.351406,0.123305,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.9237
1,0.173898,0.634004,0.462803,0.057147,0.220917,0.0,0.422428,0.458364,0.500005,0.157151,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.9162
2,0.169970,0.650621,0.684189,0.514917,0.529414,0.0,0.135192,0.428774,0.356623,0.530362,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8432
3,0.547938,0.220104,0.229559,0.061479,0.110458,0.0,0.318538,0.122294,0.000000,0.125814,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,0.0,0.9010
4,0.562757,0.120408,0.132772,0.000000,0.116506,0.0,0.124535,0.000000,0.108310,0.062902,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.9819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.350652,0.294090,0.321386,0.000000,0.000000,0.0,0.000000,0.000000,0.638977,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8272
198,0.343153,0.274673,0.289150,0.170484,0.286934,0.0,0.421654,0.122294,0.187496,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.9743
199,0.444385,0.162903,0.235559,0.000000,0.055235,0.0,0.070055,0.184430,0.180361,0.133166,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.8779
200,0.309409,0.424490,0.303150,0.000000,0.000000,0.0,0.149181,0.242600,0.329816,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8206
201,0.335654,0.383835,0.273843,0.000000,0.055235,0.0,0.069327,0.294866,0.262564,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.9578

In [14]:
lightgbm = create_model('lightgbm')
tunedlightgbm = tune_model(lightgbm,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedlightgbm)

,0,1,2,14,15,16,17,18,19,20,...,188,189,191,192,193,194,195,active,Label,Score
0,0.253348,0.534948,0.396331,0.000000,0.058829,0.0,0.077542,0.367392,0.351406,0.123305,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.8648
1,0.173898,0.634004,0.462803,0.057147,0.220917,0.0,0.422428,0.458364,0.500005,0.157151,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8429
2,0.169970,0.650621,0.684189,0.514917,0.529414,0.0,0.135192,0.428774,0.356623,0.530362,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.7845
3,0.547938,0.220104,0.229559,0.061479,0.110458,0.0,0.318538,0.122294,0.000000,0.125814,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,0.0,0.8762
4,0.562757,0.120408,0.132772,0.000000,0.116506,0.0,0.124535,0.000000,0.108310,0.062902,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.9852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.350652,0.294090,0.321386,0.000000,0.000000,0.0,0.000000,0.000000,0.638977,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.8399
198,0.343153,0.274673,0.289150,0.170484,0.286934,0.0,0.421654,0.122294,0.187496,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.9768
199,0.444385,0.162903,0.235559,0.000000,0.055235,0.0,0.070055,0.184430,0.180361,0.133166,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.8301
200,0.309409,0.424490,0.303150,0.000000,0.000000,0.0,0.149181,0.242600,0.329816,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,1.0,1.0,0.6149
201,0.335654,0.383835,0.273843,0.000000,0.055235,0.0,0.069327,0.294866,0.262564,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0625,0.0,1.0,1.0,0.9723

In [31]:
from itertools import combinations
ml = [tunedrf, tunedet, tunedlightgbm, tunedcat1, tunedxgb,tunedmlp]
a2 =  list(combinations(ml, 2))
a3 =  list(combinations(ml, 3))
a4 =  list(combinations(ml, 4))
a5 =  list(combinations(ml, 5))
a6 =  list(combinations(ml, 6))

all = a2 + a3 + a4 + a5 + a6 
print(len(all))
print(len(a2),len(a3),len(a4),len(a5),len(a6))

57
15 20 15 6 1

In [16]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['Accuracy']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False), ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=0, verbose=0,
                     warm_start=False), <catboost.core.CatBoostClassifier object at 0x7ffaf0d17f40>, XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=0, reg_alpha=0, ...)) 0.8762

In [32]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['AUC']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight='balanced',
                       criterion='entropy', max_depth=11, max_features=0.4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=4.233505241268374e-06,
                       min_impurity_split=None, min_samples_leaf=3,
                       min_samples_split=3, min_weight_fraction_leaf=0.0,
                       n_estimators=300, n_jobs=-1, oob_score=False,
                       random_state=0, verbose=0, warm_start=False), ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight='balanced',
                     criterion='entropy', max_depth=11, max_features=0.4,
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0008680975479166642,
                     min_impurity_split=None, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=162, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False), XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1,
              colsample_bytree=0.6433960368460392, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.09011146193612624,
              max_bin=256, max_cat_to_onehot=4, max_delta_step=0, max_depth=11,
              max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=192, n_jobs=-1,
              num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=0, reg_alpha=1e-10, ...), MLPClassifier(activation='relu', alpha=0.9999999998999984, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=[62, 100], learning_rate='invscaling',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=0, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)) 0.9328
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] bagging_fraction is set=0.8630341057173361, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8630341057173361
[LightGBM] [Warning] feature_fraction is set=0.4156734602227081, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4156734602227081
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6

In [35]:
blend = blend_models([tunedxgb, tunedmlp, tunedrf, tunedet])
md = predict_model(blend,data = test1)
md
y_pred = md['Label']
y_true = md['active']
t = y_pred.astype(float)
t
from sklearn.metrics import balanced_accuracy_score
accuracy = balanced_accuracy_score(y_true, t)
accuracy

0.8811028982688194