In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('padel.csv')
df.replace(to_replace='#NAME?',value=np.nan,inplace=True)
df.replace(to_replace=r'^\s*$',value=np.nan,regex=True,inplace=True)
columns = df.columns
df = df.astype("float", errors = "ignore")
df = np.float32(df)
df[np.isnan(df)] = 0
df[np.isinf(df)] = 0
df=pd.DataFrame(df,columns=columns)
ncol = df.shape[1]-1
x = df.iloc[:,0:ncol]
y = df['active']
corr_matrix = x.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
x1 = x.drop(to_drop, axis=1)
x2 = x1.loc[:, (x1 != x1.iloc[0]).any()] 
x2 = x2.round(6)

In [2]:
x1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE1_D,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP
0,0.0,-0.5644,0.318547,47.543701,74.387413,22.0,0.0,5.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
1,0.0,0.3078,0.094741,52.823002,44.257858,6.0,0.0,3.0,1.0,0.0,...,0.051235,0.002697,-5.645543,1.356911e+02,7.141639,9.329724,35.580002,0.000000,14.690436,1.415
2,0.0,-1.0727,1.150685,93.090698,77.521790,12.0,0.0,5.0,4.0,0.0,...,0.514679,0.014297,-2.391165,3.713096e+02,10.314156,21.301331,98.660004,3.044522,0.000000,3.166
3,0.0,-1.4939,2.231737,24.015100,22.764757,5.0,0.0,6.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
4,0.0,-1.3468,1.813870,69.866600,69.042999,12.0,0.0,3.0,3.0,0.0,...,0.146592,0.004729,-5.952321,2.530366e+02,8.162471,17.153955,90.459999,2.397895,16.841803,5.567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,0.0,2.3283,5.420981,67.304199,40.111446,0.0,0.0,0.0,1.0,0.0,...,0.249107,0.016607,-2.084809,8.790775e+01,5.860517,6.714432,17.070000,0.000000,2.456459,4.356
2020,0.0,0.0777,0.006037,29.923599,46.257858,12.0,0.0,2.0,1.0,0.0,...,0.000000,0.000000,-71.116287,3.000092e+06,150004.609375,29.828306,23.549999,0.000000,9.296835,5.566
2021,0.0,-1.7093,2.921706,17.461399,24.118723,6.0,0.0,1.0,2.0,0.0,...,0.033641,0.003058,-3.731219,6.601173e+01,6.001067,4.608816,66.480003,0.000000,7.402304,0.074
2022,1.0,-0.9485,0.899652,75.366203,54.621376,0.0,0.0,0.0,2.0,0.0,...,0.028600,0.001430,-7.108672,1.702734e+02,8.513672,10.274811,37.299999,0.000000,4.764172,7.865
2023,0.0,-10.4814,109.859749,194.479797,127.427582,0.0,0.0,0.0,30.0,0.0,...,0.000000,0.000000,-221.218307,9.036049e+02,13.690983,44.922188,474.899994,0.000000,0.000000,-11.796

In [3]:
x1.to_csv('output_file.csv')

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_val_test,y_train,y_val_test = train_test_split(x2,y,test_size = 0.2,random_state = 3)
x_val, x_test, y_val, y_test = train_test_split(x_val_test,y_val_test,test_size = 0.5,random_state = 3)

In [5]:
train = pd.concat([x_train,y_train],axis=1)
train

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1600,0.0,-4.0040,16.032017,49.718700,43.897823,0.0,0.0,0.0,4.0,1.0,...,0.005580,-4.004178,130.569916,7.680583,8.282244,74.809998,0.000000,13.151381,4.106,0.0
979,0.0,0.3447,0.118818,49.790298,40.737514,6.0,0.0,3.0,3.0,2.0,...,0.006313,-4.029309,146.593445,7.715445,9.476560,127.449997,0.000000,0.000000,0.000,1.0
1671,0.0,-0.1416,0.020051,15.427900,22.260344,6.0,0.0,2.0,3.0,0.0,...,0.000917,-5.411889,73.015038,6.084587,5.148799,78.389999,0.000000,13.148646,1.209,0.0
216,0.0,0.5146,0.264813,26.069201,60.197102,24.0,0.0,8.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
1692,0.0,0.3162,0.099982,15.041000,8.749172,0.0,0.0,0.0,1.0,0.0,...,0.000000,0.000000,8.452347,2.113087,0.853778,20.230000,0.000000,2.310660,-0.231,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952,0.0,1.2873,1.657141,93.338402,57.234203,0.0,0.0,0.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,34.139999,2.397895,0.000000,0.000,1.0
1667,1.0,-0.9897,0.979506,11.441400,19.691551,6.0,0.0,1.0,2.0,0.0,...,0.005150,-2.966171,58.626312,5.862631,4.071184,63.320000,0.000000,7.332074,1.643,0.0
1273,0.0,-0.4458,0.198738,17.559000,11.686758,0.0,0.0,0.0,3.0,0.0,...,0.000000,-20.918999,22.424192,3.737365,1.866084,27.690001,0.000000,8.812500,-0.159,0.0
1688,0.0,-0.0034,0.000012,32.797901,21.925516,0.0,0.0,0.0,2.0,0.0,...,0.009978,-2.169178,37.381947,4.153550,3.259069,26.299999,0.000000,5.334351,1.883,0.0
1898,4.0,-1.1790,1.390041,45.218800,27.163931,0.0,0.0,0.0,8.0,0.0,...,0.000000,-54.871124,89.407043,5.587940,7.189119,149.199997,0.000000,19.206852,-1.890,0.0

In [6]:
val = pd.concat([x_val,y_val],axis=1)
val

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
768,0.0,-0.1404,0.019712,31.230801,61.755062,23.0,0.0,3.0,3.0,1.0,...,0.006647,-4.837308,271.851288,9.061710,16.815765,113.019997,2.397895,20.610884,6.797,0.0
1493,0.0,0.0000,0.000000,0.000000,34.827930,16.0,0.0,0.0,0.0,0.0,...,0.003163,-4.774057,219.371933,13.710746,8.625230,0.000000,2.397895,0.000000,8.336,0.0
373,0.0,0.3574,0.127735,119.712692,91.117752,11.0,0.0,4.0,5.0,0.0,...,0.002718,-9.115530,775.439514,18.462845,27.944407,111.459999,3.433987,0.000000,0.000,1.0
2015,0.0,-0.8397,0.705096,12.334200,20.131552,6.0,0.0,3.0,2.0,0.0,...,0.001807,-4.309934,145.863495,13.260318,5.480938,95.180000,0.000000,12.857014,1.481,0.0
631,0.0,-5.3496,28.618219,62.618198,69.557716,6.0,0.0,0.0,3.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,60.689999,0.000000,0.000000,8.212,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,0.0,-2.7194,7.395136,69.238503,88.832916,18.0,0.0,3.0,4.0,0.0,...,0.003839,-7.406057,711.078613,18.232784,25.610455,98.739998,0.000000,0.000000,0.000,1.0
752,0.0,-2.4827,6.163799,60.700802,74.336586,16.0,0.0,5.0,3.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
2023,0.0,-10.4814,109.859749,194.479797,127.427582,0.0,0.0,0.0,30.0,0.0,...,0.000000,-221.218307,903.604919,13.690983,44.922188,474.899994,0.000000,0.000000,-11.796,0.0
1888,0.0,1.3021,1.695464,9.392100,19.691551,6.0,0.0,1.0,2.0,0.0,...,0.005150,-2.966171,58.626312,5.862631,4.071184,43.139999,0.000000,7.828583,3.006,0.0
1816,2.0,5.3028,28.119688,124.283798,64.118202,0.0,0.0,0.0,4.0,0.0,...,0.000000,-95.964256,271.707153,9.703827,15.693230,74.599998,0.000000,9.517188,6.282,0.0

In [29]:
test1 = pd.concat([x_test,y_test],axis=1)
test1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1518,0.0,0.8082,0.653187,31.407900,17.931549,0.0,0.0,1.0,2.0,0.0,...,0.008277,-2.337304,115.566147,12.840683,4.274859,50.090000,0.000000,7.645958,0.597,0.0
288,0.0,-1.8335,3.361722,54.296299,59.874203,11.0,0.0,4.0,2.0,0.0,...,0.007401,-4.284872,364.813110,14.031274,15.338402,70.250000,3.044522,18.082766,0.000,1.0
1915,0.0,2.2061,4.866877,28.361900,22.512379,6.0,0.0,0.0,1.0,0.0,...,0.003198,-3.442631,45.778889,4.577889,3.823823,20.230000,0.000000,9.961835,3.135,0.0
456,0.0,-1.0657,1.135716,61.241699,61.565445,12.0,0.0,0.0,8.0,0.0,...,0.003727,-6.690089,331.962952,10.708482,17.995571,0.000000,2.397895,21.163204,0.000,1.0
751,0.0,-3.3724,11.373082,47.613701,50.900272,6.0,0.0,0.0,9.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,0.0,-0.0012,0.000001,15.692200,10.359965,0.0,0.0,1.0,3.0,0.0,...,0.012688,-1.545196,21.339476,3.556579,1.836335,63.369999,0.000000,9.978216,-0.527,0.0
1290,0.0,0.0807,0.006512,22.736200,13.077965,0.0,0.0,1.0,2.0,0.0,...,0.008431,-1.980957,24.428183,3.489740,2.237016,50.090000,0.000000,7.465512,-0.447,0.0
896,0.0,0.9873,0.974761,26.826900,16.180758,0.0,0.0,1.0,0.0,2.0,...,0.000000,-21.210304,15.318544,2.553091,1.637438,0.000000,0.000000,0.000000,0.000,0.0
2012,0.0,-0.7499,0.562350,4.222100,29.554724,12.0,0.0,1.0,0.0,0.0,...,0.003717,-3.938825,72.218536,5.555272,5.563606,26.020000,0.000000,2.547069,4.996,0.0
1343,1.0,-1.6792,2.819713,28.118700,25.191137,5.0,0.0,1.0,5.0,0.0,...,0.007587,-3.139153,109.704544,7.836039,6.576907,99.769997,2.397895,15.730219,-0.820,0.0

In [8]:
col_name = train.columns.values.tolist()
col_name.pop()

'active'

In [9]:
from pycaret.classification import *
CM = setup(data = train, target = 'active', test_data = val, silent=True, numeric_features = col_name,
             session_id=0, fold_strategy = 'stratifiedkfold', fold = 5, fold_shuffle = True, normalize = True, normalize_method = 'minmax')

In [10]:
mlp = create_model('mlp')
tunedmlp = tune_model(mlp,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedmlp)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.739634,0.000040,0.082728,0.193646,0.766667,0.0,0.066667,0.103448,0.25,...,0.000019,0.000009,0.195689,0.107446,0.500000,0.552176,0.601452,0.0,1.0,0.8441
1,0.0,0.744319,0.000000,0.000000,0.109210,0.533333,0.0,0.000000,0.000000,0.00,...,0.000016,0.000014,0.100374,0.000000,0.500000,0.000000,0.700334,0.0,0.0,0.6461
2,0.0,0.756245,0.000257,0.317109,0.285719,0.366667,0.0,0.088889,0.172414,0.00,...,0.000055,0.000018,0.325195,0.105963,0.716042,0.000000,0.164739,1.0,1.0,0.9541
3,0.0,0.716298,0.001417,0.032672,0.063127,0.200000,0.0,0.066667,0.068966,0.00,...,0.000010,0.000013,0.063783,0.090486,0.000000,0.344446,0.259895,0.0,0.0,0.9740
4,0.0,0.565802,0.057523,0.165870,0.218113,0.200000,0.0,0.000000,0.103448,0.00,...,0.000000,0.000000,0.000000,0.057697,0.000000,0.000000,0.692367,1.0,1.0,0.5654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.653572,0.014864,0.183407,0.278555,0.600000,0.0,0.066667,0.137931,0.00,...,0.000051,0.000018,0.298034,0.093870,0.000000,0.000000,0.164739,1.0,1.0,0.9462
198,0.0,0.661471,0.012389,0.160791,0.233098,0.533333,0.0,0.111111,0.103448,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.164739,1.0,1.0,0.9353
199,0.0,0.394554,0.220818,0.515161,0.399577,0.000000,0.0,0.000000,1.034483,0.00,...,0.000065,0.000014,0.522769,0.451477,0.000000,0.000000,-0.593164,0.0,0.0,0.9328
200,0.0,0.787770,0.003408,0.024879,0.061747,0.200000,0.0,0.022222,0.068966,0.00,...,0.000004,0.000006,0.047377,0.041012,0.000000,0.209732,0.357877,0.0,0.0,0.9802
201,0.5,0.921273,0.056521,0.329217,0.201056,0.000000,0.0,0.000000,0.137931,0.00,...,0.000019,0.000010,0.182625,0.070921,0.000000,0.254970,0.568363,0.0,1.0,0.7395

In [11]:
xgb = create_model('xgboost')
tunedxgb = tune_model(xgb,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedxgb)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.739634,0.000040,0.082728,0.193646,0.766667,0.0,0.066667,0.103448,0.25,...,0.000019,0.000009,0.195689,0.107446,0.500000,0.552176,0.601452,0.0,1.0,0.9698
1,0.0,0.744319,0.000000,0.000000,0.109210,0.533333,0.0,0.000000,0.000000,0.00,...,0.000016,0.000014,0.100374,0.000000,0.500000,0.000000,0.700334,0.0,0.0,0.9638
2,0.0,0.756245,0.000257,0.317109,0.285719,0.366667,0.0,0.088889,0.172414,0.00,...,0.000055,0.000018,0.325195,0.105963,0.716042,0.000000,0.164739,1.0,1.0,0.9987
3,0.0,0.716298,0.001417,0.032672,0.063127,0.200000,0.0,0.066667,0.068966,0.00,...,0.000010,0.000013,0.063783,0.090486,0.000000,0.344446,0.259895,0.0,0.0,0.9971
4,0.0,0.565802,0.057523,0.165870,0.218113,0.200000,0.0,0.000000,0.103448,0.00,...,0.000000,0.000000,0.000000,0.057697,0.000000,0.000000,0.692367,1.0,1.0,0.9801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.653572,0.014864,0.183407,0.278555,0.600000,0.0,0.066667,0.137931,0.00,...,0.000051,0.000018,0.298034,0.093870,0.000000,0.000000,0.164739,1.0,1.0,0.9995
198,0.0,0.661471,0.012389,0.160791,0.233098,0.533333,0.0,0.111111,0.103448,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.164739,1.0,1.0,0.9961
199,0.0,0.394554,0.220818,0.515161,0.399577,0.000000,0.0,0.000000,1.034483,0.00,...,0.000065,0.000014,0.522769,0.451477,0.000000,0.000000,-0.593164,0.0,1.0,0.8833
200,0.0,0.787770,0.003408,0.024879,0.061747,0.200000,0.0,0.022222,0.068966,0.00,...,0.000004,0.000006,0.047377,0.041012,0.000000,0.209732,0.357877,0.0,0.0,0.9991
201,0.5,0.921273,0.056521,0.329217,0.201056,0.000000,0.0,0.000000,0.137931,0.00,...,0.000019,0.000010,0.182625,0.070921,0.000000,0.254970,0.568363,0.0,1.0,0.9979

In [12]:
rf = create_model('rf')
tunedrf = tune_model(rf, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedrf)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.739634,0.000040,0.082728,0.193646,0.766667,0.0,0.066667,0.103448,0.25,...,0.000019,0.000009,0.195689,0.107446,0.500000,0.552176,0.601452,0.0,1.0,0.6679
1,0.0,0.744319,0.000000,0.000000,0.109210,0.533333,0.0,0.000000,0.000000,0.00,...,0.000016,0.000014,0.100374,0.000000,0.500000,0.000000,0.700334,0.0,0.0,0.9511
2,0.0,0.756245,0.000257,0.317109,0.285719,0.366667,0.0,0.088889,0.172414,0.00,...,0.000055,0.000018,0.325195,0.105963,0.716042,0.000000,0.164739,1.0,1.0,0.9439
3,0.0,0.716298,0.001417,0.032672,0.063127,0.200000,0.0,0.066667,0.068966,0.00,...,0.000010,0.000013,0.063783,0.090486,0.000000,0.344446,0.259895,0.0,0.0,0.9921
4,0.0,0.565802,0.057523,0.165870,0.218113,0.200000,0.0,0.000000,0.103448,0.00,...,0.000000,0.000000,0.000000,0.057697,0.000000,0.000000,0.692367,1.0,1.0,0.5772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.653572,0.014864,0.183407,0.278555,0.600000,0.0,0.066667,0.137931,0.00,...,0.000051,0.000018,0.298034,0.093870,0.000000,0.000000,0.164739,1.0,1.0,0.8407
198,0.0,0.661471,0.012389,0.160791,0.233098,0.533333,0.0,0.111111,0.103448,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.164739,1.0,1.0,0.8342
199,0.0,0.394554,0.220818,0.515161,0.399577,0.000000,0.0,0.000000,1.034483,0.00,...,0.000065,0.000014,0.522769,0.451477,0.000000,0.000000,-0.593164,0.0,0.0,0.5081
200,0.0,0.787770,0.003408,0.024879,0.061747,0.200000,0.0,0.022222,0.068966,0.00,...,0.000004,0.000006,0.047377,0.041012,0.000000,0.209732,0.357877,0.0,0.0,0.9925
201,0.5,0.921273,0.056521,0.329217,0.201056,0.000000,0.0,0.000000,0.137931,0.00,...,0.000019,0.000010,0.182625,0.070921,0.000000,0.254970,0.568363,0.0,1.0,0.9417

In [13]:
et = create_model('et')
tunedet = tune_model(et, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedet)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.739634,0.000040,0.082728,0.193646,0.766667,0.0,0.066667,0.103448,0.25,...,0.000019,0.000009,0.195689,0.107446,0.500000,0.552176,0.601452,0.0,1.0,0.6498
1,0.0,0.744319,0.000000,0.000000,0.109210,0.533333,0.0,0.000000,0.000000,0.00,...,0.000016,0.000014,0.100374,0.000000,0.500000,0.000000,0.700334,0.0,0.0,0.9288
2,0.0,0.756245,0.000257,0.317109,0.285719,0.366667,0.0,0.088889,0.172414,0.00,...,0.000055,0.000018,0.325195,0.105963,0.716042,0.000000,0.164739,1.0,1.0,0.9058
3,0.0,0.716298,0.001417,0.032672,0.063127,0.200000,0.0,0.066667,0.068966,0.00,...,0.000010,0.000013,0.063783,0.090486,0.000000,0.344446,0.259895,0.0,0.0,0.9813
4,0.0,0.565802,0.057523,0.165870,0.218113,0.200000,0.0,0.000000,0.103448,0.00,...,0.000000,0.000000,0.000000,0.057697,0.000000,0.000000,0.692367,1.0,1.0,0.6054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.653572,0.014864,0.183407,0.278555,0.600000,0.0,0.066667,0.137931,0.00,...,0.000051,0.000018,0.298034,0.093870,0.000000,0.000000,0.164739,1.0,1.0,0.8699
198,0.0,0.661471,0.012389,0.160791,0.233098,0.533333,0.0,0.111111,0.103448,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.164739,1.0,1.0,0.8531
199,0.0,0.394554,0.220818,0.515161,0.399577,0.000000,0.0,0.000000,1.034483,0.00,...,0.000065,0.000014,0.522769,0.451477,0.000000,0.000000,-0.593164,0.0,1.0,0.5624
200,0.0,0.787770,0.003408,0.024879,0.061747,0.200000,0.0,0.022222,0.068966,0.00,...,0.000004,0.000006,0.047377,0.041012,0.000000,0.209732,0.357877,0.0,0.0,0.9957
201,0.5,0.921273,0.056521,0.329217,0.201056,0.000000,0.0,0.000000,0.137931,0.00,...,0.000019,0.000010,0.182625,0.070921,0.000000,0.254970,0.568363,0.0,1.0,0.8817

In [14]:
catboost = create_model('catboost')
tunedcat1 = tune_model(catboost, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedcat1)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.739634,0.000040,0.082728,0.193646,0.766667,0.0,0.066667,0.103448,0.25,...,0.000019,0.000009,0.195689,0.107446,0.500000,0.552176,0.601452,0.0,1.0,0.8056
1,0.0,0.744319,0.000000,0.000000,0.109210,0.533333,0.0,0.000000,0.000000,0.00,...,0.000016,0.000014,0.100374,0.000000,0.500000,0.000000,0.700334,0.0,0.0,0.9369
2,0.0,0.756245,0.000257,0.317109,0.285719,0.366667,0.0,0.088889,0.172414,0.00,...,0.000055,0.000018,0.325195,0.105963,0.716042,0.000000,0.164739,1.0,1.0,0.9609
3,0.0,0.716298,0.001417,0.032672,0.063127,0.200000,0.0,0.066667,0.068966,0.00,...,0.000010,0.000013,0.063783,0.090486,0.000000,0.344446,0.259895,0.0,0.0,0.9914
4,0.0,0.565802,0.057523,0.165870,0.218113,0.200000,0.0,0.000000,0.103448,0.00,...,0.000000,0.000000,0.000000,0.057697,0.000000,0.000000,0.692367,1.0,1.0,0.5207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.653572,0.014864,0.183407,0.278555,0.600000,0.0,0.066667,0.137931,0.00,...,0.000051,0.000018,0.298034,0.093870,0.000000,0.000000,0.164739,1.0,1.0,0.9760
198,0.0,0.661471,0.012389,0.160791,0.233098,0.533333,0.0,0.111111,0.103448,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.164739,1.0,1.0,0.9377
199,0.0,0.394554,0.220818,0.515161,0.399577,0.000000,0.0,0.000000,1.034483,0.00,...,0.000065,0.000014,0.522769,0.451477,0.000000,0.000000,-0.593164,0.0,1.0,0.5371
200,0.0,0.787770,0.003408,0.024879,0.061747,0.200000,0.0,0.022222,0.068966,0.00,...,0.000004,0.000006,0.047377,0.041012,0.000000,0.209732,0.357877,0.0,0.0,0.9959
201,0.5,0.921273,0.056521,0.329217,0.201056,0.000000,0.0,0.000000,0.137931,0.00,...,0.000019,0.000010,0.182625,0.070921,0.000000,0.254970,0.568363,0.0,1.0,0.9108

In [15]:
lightgbm = create_model('lightgbm')
tunedlightgbm = tune_model(lightgbm,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedlightgbm)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.0,0.739634,0.000040,0.082728,0.193646,0.766667,0.0,0.066667,0.103448,0.25,...,0.000019,0.000009,0.195689,0.107446,0.500000,0.552176,0.601452,0.0,1.0,0.8809
1,0.0,0.744319,0.000000,0.000000,0.109210,0.533333,0.0,0.000000,0.000000,0.00,...,0.000016,0.000014,0.100374,0.000000,0.500000,0.000000,0.700334,0.0,0.0,0.9950
2,0.0,0.756245,0.000257,0.317109,0.285719,0.366667,0.0,0.088889,0.172414,0.00,...,0.000055,0.000018,0.325195,0.105963,0.716042,0.000000,0.164739,1.0,1.0,0.9980
3,0.0,0.716298,0.001417,0.032672,0.063127,0.200000,0.0,0.066667,0.068966,0.00,...,0.000010,0.000013,0.063783,0.090486,0.000000,0.344446,0.259895,0.0,0.0,0.9998
4,0.0,0.565802,0.057523,0.165870,0.218113,0.200000,0.0,0.000000,0.103448,0.00,...,0.000000,0.000000,0.000000,0.057697,0.000000,0.000000,0.692367,1.0,0.0,0.5079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.0,0.653572,0.014864,0.183407,0.278555,0.600000,0.0,0.066667,0.137931,0.00,...,0.000051,0.000018,0.298034,0.093870,0.000000,0.000000,0.164739,1.0,1.0,0.9998
198,0.0,0.661471,0.012389,0.160791,0.233098,0.533333,0.0,0.111111,0.103448,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.164739,1.0,1.0,0.9962
199,0.0,0.394554,0.220818,0.515161,0.399577,0.000000,0.0,0.000000,1.034483,0.00,...,0.000065,0.000014,0.522769,0.451477,0.000000,0.000000,-0.593164,0.0,0.0,0.5091
200,0.0,0.787770,0.003408,0.024879,0.061747,0.200000,0.0,0.022222,0.068966,0.00,...,0.000004,0.000006,0.047377,0.041012,0.000000,0.209732,0.357877,0.0,0.0,1.0000
201,0.5,0.921273,0.056521,0.329217,0.201056,0.000000,0.0,0.000000,0.137931,0.00,...,0.000019,0.000010,0.182625,0.070921,0.000000,0.254970,0.568363,0.0,1.0,0.9965

In [27]:
from itertools import combinations
ml = [tunedrf, tunedet, tunedlightgbm, tunedcat1, tunedxgb,tunedmlp]
a2 =  list(combinations(ml, 2))
a3 =  list(combinations(ml, 3))
a4 =  list(combinations(ml, 4))
a5 =  list(combinations(ml, 5))
a6 =  list(combinations(ml, 6))

all = a2 + a3 + a4 + a5 + a6 
print(len(all))
print(len(a2),len(a3),len(a4),len(a5),len(a6))

57
15 20 15 6 1

In [17]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['Accuracy']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False), LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=0, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)) 0.8911

In [28]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['AUC']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=11, max_features=0.4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=1e-09, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False), ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='entropy', max_depth=11, max_features=1.0,
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.00010291735892094771,
                     min_impurity_split=None, min_samples_leaf=2,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=231, n_jobs=-1, oob_score=False,
                     random_state=0, verbose=0, warm_start=False)) 0.9471
[LightGBM] [Warning] bagging_fraction is set=0.6742999875048314, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6742999875048314
[LightGBM] [Warning] feature_fraction is set=0.776407185158853, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.776407185158853
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0

In [30]:
blend = blend_models([tunedrf, tunedet])
md = predict_model(blend,data = test1)
md
y_pred = md['Label']
y_true = md['active']
t = y_pred.astype(float)
t
from sklearn.metrics import balanced_accuracy_score
accuracy = balanced_accuracy_score(y_true, t)
accuracy

0.8850928641251221