In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('padel.csv')
df.replace(to_replace='#NAME?',value=np.nan,inplace=True)
df.replace(to_replace=r'^\s*$',value=np.nan,regex=True,inplace=True)
columns = df.columns
df = df.astype("float", errors = "ignore")
df = np.float32(df)
df[np.isnan(df)] = 0
df[np.isinf(df)] = 0
df=pd.DataFrame(df,columns=columns)
ncol = df.shape[1]-1
x = df.iloc[:,0:ncol]
y = df['active']
corr_matrix = x.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
x1 = x.drop(to_drop, axis=1)
x2 = x1.loc[:, (x1 != x1.iloc[0]).any()] 
x2 = x2.round(6)

In [2]:
x1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE1_D,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP
0,0.0,-0.5644,0.318547,47.543701,74.387413,22.0,0.0,5.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
1,0.0,0.3078,0.094741,52.823002,44.257858,6.0,0.0,3.0,1.0,0.0,...,0.051235,0.002697,-5.645543,1.356911e+02,7.141639,9.329724,35.580002,0.000000,14.690436,1.415
2,0.0,-1.0727,1.150685,93.090698,77.521790,12.0,0.0,5.0,4.0,0.0,...,0.514679,0.014297,-2.391165,3.713096e+02,10.314156,21.301331,98.660004,3.044522,0.000000,3.166
3,0.0,-1.4939,2.231737,24.015100,22.764757,5.0,0.0,6.0,2.0,0.0,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
4,0.0,-1.3468,1.813870,69.866600,69.042999,12.0,0.0,3.0,3.0,0.0,...,0.146592,0.004729,-5.952321,2.530366e+02,8.162471,17.153955,90.459999,2.397895,16.841803,5.567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,0.0,2.3283,5.420981,67.304199,40.111446,0.0,0.0,0.0,1.0,0.0,...,0.249107,0.016607,-2.084809,8.790775e+01,5.860517,6.714432,17.070000,0.000000,2.456459,4.356
2020,0.0,0.0777,0.006037,29.923599,46.257858,12.0,0.0,2.0,1.0,0.0,...,0.000000,0.000000,-71.116287,3.000092e+06,150004.609375,29.828306,23.549999,0.000000,9.296835,5.566
2021,0.0,-1.7093,2.921706,17.461399,24.118723,6.0,0.0,1.0,2.0,0.0,...,0.033641,0.003058,-3.731219,6.601173e+01,6.001067,4.608816,66.480003,0.000000,7.402304,0.074
2022,1.0,-0.9485,0.899652,75.366203,54.621376,0.0,0.0,0.0,2.0,0.0,...,0.028600,0.001430,-7.108672,1.702734e+02,8.513672,10.274811,37.299999,0.000000,4.764172,7.865
2023,0.0,-10.4814,109.859749,194.479797,127.427582,0.0,0.0,0.0,30.0,0.0,...,0.000000,0.000000,-221.218307,9.036049e+02,13.690983,44.922188,474.899994,0.000000,0.000000,-11.796

In [3]:
x1.to_csv('output_file.csv')

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_val_test,y_train,y_val_test = train_test_split(x2,y,test_size = 0.2,random_state = 2)
x_val, x_test, y_val, y_test = train_test_split(x_val_test,y_val_test,test_size = 0.5,random_state = 2)

In [5]:
train = pd.concat([x_train,y_train],axis=1)
train

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
515,0.0,1.3195,1.741080,41.534801,61.745861,21.0,0.0,5.0,0.0,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
1794,0.0,-1.0645,1.133160,25.290400,31.101103,6.0,0.0,0.0,3.0,0.0,...,0.012694,-2.418617,159.211487,11.372249,7.098327,46.529999,0.000000,8.014176,2.741,0.0
333,0.0,-0.2498,0.062400,48.758999,43.293068,6.0,0.0,2.0,2.0,0.0,...,0.004056,-4.869699,140.741806,7.407463,9.399161,41.570000,0.000000,0.000000,0.000,1.0
734,0.0,1.8799,3.534024,90.118103,76.176758,6.0,0.0,2.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
1753,0.0,1.0326,1.066263,25.346800,14.567551,0.0,0.0,1.0,0.0,0.0,...,0.000000,-21.626192,18.981178,3.163530,1.766069,23.790001,0.000000,2.388325,1.056,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,0.0,-0.7499,0.562350,4.222100,16.327551,6.0,0.0,1.0,0.0,0.0,...,0.001636,-3.128850,28.150736,4.021534,2.336301,26.020000,0.000000,2.490697,1.977,0.0
1608,1.0,-1.4137,1.998548,61.031799,50.237068,6.0,0.0,3.0,4.0,1.0,...,0.006776,-4.359308,194.574371,8.107266,12.649955,138.029999,2.397895,22.075514,-0.296,0.0
493,0.0,-0.8216,0.675027,33.446899,53.347858,17.0,0.0,0.0,6.0,0.0,...,0.003737,-6.061805,397.959106,15.306119,15.564508,70.290001,2.397895,16.856085,0.000,1.0
527,0.0,-0.0843,0.007106,32.657299,49.679482,17.0,0.0,3.0,2.0,0.0,...,0.001582,-7.850412,302.430450,12.601269,13.708443,60.169998,2.397895,14.915932,4.927,1.0
1192,0.0,-0.1366,0.018660,10.430200,34.671928,12.0,0.0,0.0,2.0,0.0,...,0.005847,-3.924554,153.944946,9.055585,8.562212,17.070000,0.000000,5.747701,4.859,0.0

In [6]:
val = pd.concat([x_val,y_val],axis=1)
val

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1230,0.0,-0.3465,0.120062,7.913000,13.071172,5.0,0.0,0.0,2.0,0.0,...,0.017762,-1.459347,3.574373e+01,5.106248,2.503462,30.209999,2.397895,5.383752,1.057,0.0
1255,0.0,0.1637,0.026798,23.499701,13.799551,0.0,0.0,0.0,1.0,0.0,...,0.000000,-18.021828,2.000004e+06,400000.843750,7.254330,20.230000,0.000000,4.724874,0.962,0.0
268,0.0,-0.3613,0.130538,30.882299,49.892273,17.0,0.0,2.0,5.0,0.0,...,0.005789,-4.832277,7.454866e+02,29.819464,16.535093,0.000000,0.000000,0.000000,0.000,1.0
1922,0.0,1.3202,1.742928,7.780000,18.635172,6.0,0.0,2.0,4.0,0.0,...,0.000000,-41.837997,4.000029e+06,333335.750000,18.242174,86.279999,0.000000,15.710983,2.570,0.0
1568,0.0,0.9486,0.899842,29.443300,16.361551,0.0,0.0,0.0,2.0,0.0,...,0.008431,-1.980957,2.442818e+01,3.489740,2.237016,26.299999,0.000000,7.579520,1.239,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677,0.0,0.9099,0.827918,25.358299,38.908344,15.0,0.0,5.0,2.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,22.157242,2.247,1.0
1206,0.0,3.5281,12.447490,56.313999,39.750725,6.0,0.0,1.0,3.0,1.0,...,0.003147,-5.167595,1.051457e+02,5.841428,8.379626,82.480003,0.000000,25.430136,4.216,0.0
352,0.0,-1.2122,1.469429,9.079400,37.673931,19.0,0.0,2.0,3.0,0.0,...,0.004197,-4.955071,5.214741e+02,26.073702,12.513319,78.330002,3.433987,15.006766,0.000,1.0
1780,0.0,1.1560,1.336336,17.763100,23.131138,6.0,0.0,0.0,0.0,0.0,...,0.014683,-1.821442,7.438585e+01,8.265094,3.878339,0.000000,0.000000,2.433334,5.001,0.0
1758,1.0,-0.4934,0.243444,19.097099,11.686758,0.0,0.0,0.0,3.0,0.0,...,0.012688,-1.545196,2.133948e+01,3.556579,1.836335,46.529999,0.000000,7.342074,-0.598,0.0

In [26]:
test1 = pd.concat([x_test,y_test],axis=1)
test1

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VE2_D,VE3_D,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active
1710,0.0,-0.9734,0.947508,18.998699,14.509930,0.0,0.0,0.0,1.0,0.0,...,0.000000,-18.021828,2.000004e+06,400000.843750,7.254330,20.230000,0.000000,2.362437,0.851,0.0
532,0.0,-0.0517,0.002673,111.986099,88.624748,11.0,0.0,4.0,5.0,0.0,...,0.002718,-9.115530,7.754395e+02,18.462845,27.944407,0.000000,0.000000,0.000000,0.000,1.0
494,0.0,-0.5354,0.286653,26.891600,53.453896,21.0,0.0,4.0,1.0,0.0,...,0.007929,-4.105836,3.783209e+02,14.550803,15.432931,84.660004,0.000000,0.000000,0.000,1.0
1008,0.0,-1.5350,2.356225,17.926901,37.077930,12.0,0.0,0.0,5.0,0.0,...,0.006427,-4.103055,2.963490e+02,14.817450,11.383076,77.760002,0.000000,0.000000,0.000,1.0
1810,0.0,-0.2539,0.064465,10.770400,18.889551,6.0,0.0,1.0,1.0,0.0,...,0.003429,-3.130551,4.871948e+01,5.413276,3.497471,29.959999,0.000000,5.402890,1.290,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,0.0,-2.1715,4.715412,82.028702,95.324135,21.0,0.0,6.0,3.0,1.0,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
3,0.0,-1.4939,2.231737,24.015100,22.764757,5.0,0.0,6.0,2.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,1.0
920,0.0,-0.6708,0.449973,32.120998,33.663101,6.0,0.0,0.0,4.0,0.0,...,0.000000,-55.555035,4.000067e+06,250004.187500,24.322914,43.520000,0.000000,0.000000,0.000,1.0
874,0.0,-0.6226,0.387631,25.387199,51.419102,18.0,0.0,8.0,2.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,27.804310,0.000,0.0
558,0.0,-0.6547,0.428632,53.107800,70.230064,22.0,0.0,8.0,2.0,0.0,...,0.000487,-14.858270,4.090834e+03,110.563087,30.771067,95.559998,3.044522,0.000000,0.000,1.0

In [8]:
col_name = train.columns.values.tolist()
col_name.pop()

'active'

In [9]:
from pycaret.classification import *
CM = setup(data = train, target = 'active', test_data = val, silent=True, numeric_features = col_name,
             session_id=0, fold_strategy = 'stratifiedkfold', fold = 5, fold_shuffle = True, normalize = True, normalize_method = 'minmax')

In [10]:
mlp = create_model('mlp')
tunedmlp = tune_model(mlp,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedmlp)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.795373,0.000241,0.020961,0.040987,0.15625,0.0,0.000000,0.066667,0.00,...,0.000003,0.000005,0.029133,0.028720,0.500000,0.139060,0.418978,0.0,0.0,0.9579
1,0.00,0.813853,0.000054,0.062249,0.043271,0.00000,0.0,0.000000,0.033333,0.00,...,0.142857,0.400001,0.084420,0.019232,0.000000,0.122041,0.415882,0.0,0.0,0.9748
2,0.00,0.794837,0.000262,0.081805,0.156448,0.53125,0.0,0.044444,0.166667,0.00,...,0.000053,0.000030,0.192422,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.8307
3,0.00,0.855744,0.003503,0.020609,0.058435,0.18750,0.0,0.044444,0.133333,0.00,...,0.285716,0.333336,0.212288,0.082025,0.000000,0.405807,0.468299,0.0,0.0,0.9854
4,0.00,0.842284,0.001809,0.077993,0.051305,0.00000,0.0,0.000000,0.066667,0.00,...,0.000002,0.000003,0.026033,0.025003,0.000000,0.195775,0.424911,0.0,0.0,0.9837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.840882,0.001664,0.067172,0.122005,0.46875,0.0,0.111111,0.066667,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.572310,0.457770,1.0,1.0,0.9319
198,0.00,0.935718,0.025019,0.149171,0.124647,0.18750,0.0,0.022222,0.100000,0.25,...,0.000008,0.000006,0.097515,0.078412,0.000000,0.656847,0.521955,0.0,0.0,0.8696
199,0.00,0.764016,0.002954,0.024051,0.118135,0.59375,0.0,0.044444,0.100000,0.00,...,0.000037,0.000026,0.145620,0.074467,0.716042,0.387617,0.384523,1.0,1.0,0.8263
200,0.00,0.849796,0.002686,0.047053,0.072533,0.18750,0.0,0.000000,0.000000,0.00,...,0.000005,0.000008,0.045133,0.000000,0.000000,0.062852,0.547544,0.0,0.0,0.8189
201,0.25,0.790052,0.000489,0.050587,0.036646,0.00000,0.0,0.000000,0.100000,0.00,...,0.000002,0.000004,0.021370,0.044235,0.000000,0.189642,0.365029,0.0,0.0,0.9964

In [11]:
xgb = create_model('xgboost')
tunedxgb = tune_model(xgb,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedxgb)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.795373,0.000241,0.020961,0.040987,0.15625,0.0,0.000000,0.066667,0.00,...,0.000003,0.000005,0.029133,0.028720,0.500000,0.139060,0.418978,0.0,0.0,0.9648
1,0.00,0.813853,0.000054,0.062249,0.043271,0.00000,0.0,0.000000,0.033333,0.00,...,0.142857,0.400001,0.084420,0.019232,0.000000,0.122041,0.415882,0.0,0.0,0.9785
2,0.00,0.794837,0.000262,0.081805,0.156448,0.53125,0.0,0.044444,0.166667,0.00,...,0.000053,0.000030,0.192422,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9646
3,0.00,0.855744,0.003503,0.020609,0.058435,0.18750,0.0,0.044444,0.133333,0.00,...,0.285716,0.333336,0.212288,0.082025,0.000000,0.405807,0.468299,0.0,0.0,0.9709
4,0.00,0.842284,0.001809,0.077993,0.051305,0.00000,0.0,0.000000,0.066667,0.00,...,0.000002,0.000003,0.026033,0.025003,0.000000,0.195775,0.424911,0.0,0.0,0.9668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.840882,0.001664,0.067172,0.122005,0.46875,0.0,0.111111,0.066667,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.572310,0.457770,1.0,1.0,0.8716
198,0.00,0.935718,0.025019,0.149171,0.124647,0.18750,0.0,0.022222,0.100000,0.25,...,0.000008,0.000006,0.097515,0.078412,0.000000,0.656847,0.521955,0.0,0.0,0.9212
199,0.00,0.764016,0.002954,0.024051,0.118135,0.59375,0.0,0.044444,0.100000,0.00,...,0.000037,0.000026,0.145620,0.074467,0.716042,0.387617,0.384523,1.0,1.0,0.8820
200,0.00,0.849796,0.002686,0.047053,0.072533,0.18750,0.0,0.000000,0.000000,0.00,...,0.000005,0.000008,0.045133,0.000000,0.000000,0.062852,0.547544,0.0,0.0,0.8059
201,0.25,0.790052,0.000489,0.050587,0.036646,0.00000,0.0,0.000000,0.100000,0.00,...,0.000002,0.000004,0.021370,0.044235,0.000000,0.189642,0.365029,0.0,0.0,0.9786

In [12]:
rf = create_model('rf')
tunedrf = tune_model(rf, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedrf)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.795373,0.000241,0.020961,0.040987,0.15625,0.0,0.000000,0.066667,0.00,...,0.000003,0.000005,0.029133,0.028720,0.500000,0.139060,0.418978,0.0,0.0,0.9104
1,0.00,0.813853,0.000054,0.062249,0.043271,0.00000,0.0,0.000000,0.033333,0.00,...,0.142857,0.400001,0.084420,0.019232,0.000000,0.122041,0.415882,0.0,0.0,0.9983
2,0.00,0.794837,0.000262,0.081805,0.156448,0.53125,0.0,0.044444,0.166667,0.00,...,0.000053,0.000030,0.192422,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9508
3,0.00,0.855744,0.003503,0.020609,0.058435,0.18750,0.0,0.044444,0.133333,0.00,...,0.285716,0.333336,0.212288,0.082025,0.000000,0.405807,0.468299,0.0,0.0,0.9851
4,0.00,0.842284,0.001809,0.077993,0.051305,0.00000,0.0,0.000000,0.066667,0.00,...,0.000002,0.000003,0.026033,0.025003,0.000000,0.195775,0.424911,0.0,0.0,0.9898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.840882,0.001664,0.067172,0.122005,0.46875,0.0,0.111111,0.066667,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.572310,0.457770,1.0,1.0,0.6852
198,0.00,0.935718,0.025019,0.149171,0.124647,0.18750,0.0,0.022222,0.100000,0.25,...,0.000008,0.000006,0.097515,0.078412,0.000000,0.656847,0.521955,0.0,0.0,0.9538
199,0.00,0.764016,0.002954,0.024051,0.118135,0.59375,0.0,0.044444,0.100000,0.00,...,0.000037,0.000026,0.145620,0.074467,0.716042,0.387617,0.384523,1.0,1.0,0.7945
200,0.00,0.849796,0.002686,0.047053,0.072533,0.18750,0.0,0.000000,0.000000,0.00,...,0.000005,0.000008,0.045133,0.000000,0.000000,0.062852,0.547544,0.0,0.0,0.7820
201,0.25,0.790052,0.000489,0.050587,0.036646,0.00000,0.0,0.000000,0.100000,0.00,...,0.000002,0.000004,0.021370,0.044235,0.000000,0.189642,0.365029,0.0,0.0,1.0000

In [13]:
et = create_model('et')
tunedet = tune_model(et, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedet)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.795373,0.000241,0.020961,0.040987,0.15625,0.0,0.000000,0.066667,0.00,...,0.000003,0.000005,0.029133,0.028720,0.500000,0.139060,0.418978,0.0,0.0,0.9513
1,0.00,0.813853,0.000054,0.062249,0.043271,0.00000,0.0,0.000000,0.033333,0.00,...,0.142857,0.400001,0.084420,0.019232,0.000000,0.122041,0.415882,0.0,0.0,0.9970
2,0.00,0.794837,0.000262,0.081805,0.156448,0.53125,0.0,0.044444,0.166667,0.00,...,0.000053,0.000030,0.192422,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9102
3,0.00,0.855744,0.003503,0.020609,0.058435,0.18750,0.0,0.044444,0.133333,0.00,...,0.285716,0.333336,0.212288,0.082025,0.000000,0.405807,0.468299,0.0,0.0,0.9701
4,0.00,0.842284,0.001809,0.077993,0.051305,0.00000,0.0,0.000000,0.066667,0.00,...,0.000002,0.000003,0.026033,0.025003,0.000000,0.195775,0.424911,0.0,0.0,0.9632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.840882,0.001664,0.067172,0.122005,0.46875,0.0,0.111111,0.066667,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.572310,0.457770,1.0,1.0,0.8456
198,0.00,0.935718,0.025019,0.149171,0.124647,0.18750,0.0,0.022222,0.100000,0.25,...,0.000008,0.000006,0.097515,0.078412,0.000000,0.656847,0.521955,0.0,0.0,0.8709
199,0.00,0.764016,0.002954,0.024051,0.118135,0.59375,0.0,0.044444,0.100000,0.00,...,0.000037,0.000026,0.145620,0.074467,0.716042,0.387617,0.384523,1.0,1.0,0.6646
200,0.00,0.849796,0.002686,0.047053,0.072533,0.18750,0.0,0.000000,0.000000,0.00,...,0.000005,0.000008,0.045133,0.000000,0.000000,0.062852,0.547544,0.0,0.0,0.7552
201,0.25,0.790052,0.000489,0.050587,0.036646,0.00000,0.0,0.000000,0.100000,0.00,...,0.000002,0.000004,0.021370,0.044235,0.000000,0.189642,0.365029,0.0,0.0,0.9985

In [14]:
catboost = create_model('catboost')
tunedcat1 = tune_model(catboost, n_iter = 200,search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedcat1)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.795373,0.000241,0.020961,0.040987,0.15625,0.0,0.000000,0.066667,0.00,...,0.000003,0.000005,0.029133,0.028720,0.500000,0.139060,0.418978,0.0,0.0,0.9906
1,0.00,0.813853,0.000054,0.062249,0.043271,0.00000,0.0,0.000000,0.033333,0.00,...,0.142857,0.400001,0.084420,0.019232,0.000000,0.122041,0.415882,0.0,0.0,0.9958
2,0.00,0.794837,0.000262,0.081805,0.156448,0.53125,0.0,0.044444,0.166667,0.00,...,0.000053,0.000030,0.192422,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9722
3,0.00,0.855744,0.003503,0.020609,0.058435,0.18750,0.0,0.044444,0.133333,0.00,...,0.285716,0.333336,0.212288,0.082025,0.000000,0.405807,0.468299,0.0,0.0,0.9907
4,0.00,0.842284,0.001809,0.077993,0.051305,0.00000,0.0,0.000000,0.066667,0.00,...,0.000002,0.000003,0.026033,0.025003,0.000000,0.195775,0.424911,0.0,0.0,0.9768
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.840882,0.001664,0.067172,0.122005,0.46875,0.0,0.111111,0.066667,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.572310,0.457770,1.0,1.0,0.8192
198,0.00,0.935718,0.025019,0.149171,0.124647,0.18750,0.0,0.022222,0.100000,0.25,...,0.000008,0.000006,0.097515,0.078412,0.000000,0.656847,0.521955,0.0,0.0,0.9785
199,0.00,0.764016,0.002954,0.024051,0.118135,0.59375,0.0,0.044444,0.100000,0.00,...,0.000037,0.000026,0.145620,0.074467,0.716042,0.387617,0.384523,1.0,1.0,0.9433
200,0.00,0.849796,0.002686,0.047053,0.072533,0.18750,0.0,0.000000,0.000000,0.00,...,0.000005,0.000008,0.045133,0.000000,0.000000,0.062852,0.547544,0.0,0.0,0.9618
201,0.25,0.790052,0.000489,0.050587,0.036646,0.00000,0.0,0.000000,0.100000,0.00,...,0.000002,0.000004,0.021370,0.044235,0.000000,0.189642,0.365029,0.0,0.0,0.9957

In [15]:
lightgbm = create_model('lightgbm')
tunedlightgbm = tune_model(lightgbm,n_iter = 200, search_library = 'scikit-optimize',optimize = 'AUC')
predict_model(tunedlightgbm)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nB,nN,nO,nS,...,VR1_D,VR2_D,VR3_D,TopoPSA,SRW5,WTPT-3,XLogP,active,Label,Score
0,0.00,0.795373,0.000241,0.020961,0.040987,0.15625,0.0,0.000000,0.066667,0.00,...,0.000003,0.000005,0.029133,0.028720,0.500000,0.139060,0.418978,0.0,0.0,0.9981
1,0.00,0.813853,0.000054,0.062249,0.043271,0.00000,0.0,0.000000,0.033333,0.00,...,0.142857,0.400001,0.084420,0.019232,0.000000,0.122041,0.415882,0.0,0.0,0.9994
2,0.00,0.794837,0.000262,0.081805,0.156448,0.53125,0.0,0.044444,0.166667,0.00,...,0.000053,0.000030,0.192422,0.000000,0.000000,0.000000,0.384523,1.0,1.0,0.9933
3,0.00,0.855744,0.003503,0.020609,0.058435,0.18750,0.0,0.044444,0.133333,0.00,...,0.285716,0.333336,0.212288,0.082025,0.000000,0.405807,0.468299,0.0,0.0,0.9988
4,0.00,0.842284,0.001809,0.077993,0.051305,0.00000,0.0,0.000000,0.066667,0.00,...,0.000002,0.000003,0.026033,0.025003,0.000000,0.195775,0.424911,0.0,0.0,0.9992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,0.00,0.840882,0.001664,0.067172,0.122005,0.46875,0.0,0.111111,0.066667,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.572310,0.457770,1.0,1.0,0.9779
198,0.00,0.935718,0.025019,0.149171,0.124647,0.18750,0.0,0.022222,0.100000,0.25,...,0.000008,0.000006,0.097515,0.078412,0.000000,0.656847,0.521955,0.0,0.0,0.9945
199,0.00,0.764016,0.002954,0.024051,0.118135,0.59375,0.0,0.044444,0.100000,0.00,...,0.000037,0.000026,0.145620,0.074467,0.716042,0.387617,0.384523,1.0,1.0,0.9778
200,0.00,0.849796,0.002686,0.047053,0.072533,0.18750,0.0,0.000000,0.000000,0.00,...,0.000005,0.000008,0.045133,0.000000,0.000000,0.062852,0.547544,0.0,0.0,0.9680
201,0.25,0.790052,0.000489,0.050587,0.036646,0.00000,0.0,0.000000,0.100000,0.00,...,0.000002,0.000004,0.021370,0.044235,0.000000,0.189642,0.365029,0.0,0.0,0.9991

In [24]:
from itertools import combinations
ml = [tunedrf, tunedet, tunedlightgbm, tunedcat1, tunedxgb,tunedmlp]
a2 =  list(combinations(ml, 2))
a3 =  list(combinations(ml, 3))
a4 =  list(combinations(ml, 4))
a5 =  list(combinations(ml, 5))
a6 =  list(combinations(ml, 6))

all = a2 + a3 + a4 + a5 + a6 
print(len(all))
print(len(a2),len(a3),len(a4),len(a5),len(a6))

57
15 20 15 6 1

In [17]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['Accuracy']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(<catboost.core.CatBoostClassifier object at 0x7efc39b611f0>, XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=0, reg_alpha=0, ...)) 0.9307

In [25]:
base_score = 0
for i in all:
    blender = blend_models(i)
    predict_model(blender)
    test = pull()
    avg = test['AUC']
    avg = avg.iloc[0]
    if avg > base_score:
       base_score = avg
       best_params = i
print(best_params, base_score)

(LGBMClassifier(bagging_fraction=0.7202337964382108, bagging_freq=0,
               boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               feature_fraction=1.0, importance_type='split',
               learning_rate=0.048553937898965754, max_depth=-1,
               min_child_samples=1, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=158, n_jobs=-1, num_leaves=39, objective=None,
               random_state=0, reg_alpha=1.6411687635510933e-09,
               reg_lambda=8.79566132412341e-05, silent='warn', subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0), XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.5,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.010862357867337085, max_bin=256,
              max_cat_to_onehot=4, max_delta_step=0, max_depth=9, max_leaves=0,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=300, n_jobs=-1, num_parallel_tree=1,
              objective='binary:logistic', predictor='auto', random_state=0,
              reg_alpha=1.6693151269749602e-06, ...)) 0.9702
[LightGBM] [Warning] bagging_fraction is set=0.7202337964382108, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7202337964382108
[LightGBM] [Warning] feature_fraction is set=1.0, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=1.0
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0
[LightGBM] [Warning] bagging_fraction is set=0.7202337964382108, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7202337964382108
[LightGBM] [Warning] feature_fraction is set=1.0, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=1.0
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0
[LightGBM] [Warning] bagging_fraction is set=0.7202337964382108, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7202337964382108
[LightGBM] [Warning] feature_fraction is set=1.0, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=1.0
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0
[LightGBM] [Warning] bagging_fraction is set=0.7202337964382108, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7202337964382108
[LightGBM] [Warning] feature_fraction is set=1.0, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=1.0
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0

In [27]:
blend = blend_models([tunedxgb,tunedlightgbm])
md = predict_model(blend,data = test1)
md
y_pred = md['Label']
y_true = md['active']
t = y_pred.astype(float)
t
from sklearn.metrics import balanced_accuracy_score
accuracy = balanced_accuracy_score(y_true, t)
accuracy

0.8849802371541502